boostcampwm2023/iOS07-traveline

BE/.eslintrc.js
BE/.gitignore
BE/.prettierrc
BE/README.md
BE/nest-cli.json
BE/package-lock.json
BE/package.json
BE/src/app.controller.spec.ts
BE/src/app.controller.ts
BE/src/app.module.ts
BE/src/app.service.ts
BE/src/logging/logging.interceptor.ts
BE/src/logging/logging.logger.ts
BE/src/main.ts
BE/test/app.e2e-spec.ts
BE/test/jest-e2e.json
BE/tsconfig.build.json
BE/tsconfig.json

🌱 작업한 브랜치
- be-feature/settings
- `nest new BE` CLI로 Nest 프로젝트 생성
- winston과 winston-daily-rotate-file 모듈을 통해 매일 새 로그 파일이 생성되고 로그를 남기도록 구현
- 위 로거를 custom interceptor로 만들고, main.ts 파일에 전역 로거로 등록
- 「NestJS로 배우는 백엔드 프로그래밍」 13장: 인터셉터로 요청과 응답을 입맛에 맞게 바꾸기
📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|`log.YYYY-MM-DD` 파일|![image](https://github.com/boostcampwm2023/iOS07-Trapture/assets/62174395/50506eee-32da-42f5-9981-4dec4ec051de)|
- Resolved: # (아직...)

[feat] nest 프로젝트 및 로깅 세팅

---

BE/src/exception/exception.filter.ts
BE/src/main.ts

🌱 작업한 브랜치
- be-feature/handle-exception
- 예외처리 필터를 만들었다.
- 「NestJS로 배우는 백엔드 프로그래밍」 12장: 모든 것은 항상 실패한다: 예외처리
|기능|스크린샷|
|:--:|:--:|
|에러 메세지를 로그 파일에 출력|![image](https://github.com/boostcampwm2023/iOS07-Trapture/assets/138637345/77d6f79a-a3a9-4400-9e78-c376a21e6b8b)|
- Resolved: # (아직...)

[feat] 예외처리 필터 적용

---

iOS/.gitignore
iOS/.swiftlint.yml
iOS/Scripts/SwiftLintRunScript.sh
iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
iOS/Tuist/ProjectDescriptionHelpers/Scripts.swift
iOS/traveline/Sources/test.swift

🌱 작업한 브랜치
- feature/#5
- SwiftLint 추가 및 룰 설정
- Resolved: #5

[feat] SwiftLint 설정

---

iOS/traveline/Sources/Data/Network/API/LoginEndPoint.swift
iOS/traveline/Sources/Data/Network/Base/EndPoint.swift
iOS/traveline/Sources/Data/Network/Base/HTTPMethod.swift
iOS/traveline/Sources/Data/Network/Base/NetworkError.swift
iOS/traveline/Sources/Data/Network/Base/NetworkManager.swift

🌱 작업한 브랜치
- feature/#7
- 네트워크 레이어 구현
Network 폴더 기본 구현 사항
- NetworkManager
- HTTPMethod
- EndPoint
- NetworkError
- close #7

[feat] 네트워크 레이어 구현

---

README.md
iOS/Plugins/IOS/ProjectDescriptionHelpers/InfoPlist.swift
iOS/traveline/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
iOS/traveline/Sources/App/SceneDelegate.swift
iOS/traveline/Sources/App/ViewController.swift
iOS/traveline/Sources/DesignSystem/Component/TravelineLabel.swift
iOS/traveline/Sources/DesignSystem/TravelineFont.swift

🌱 작업한 브랜치
- feature/#16
- TravelineFont 추가
- TravelineLabel 추가
- README 내용 추가
- Resolved: #16

[chore] TravelineLabel 추가 및 README 수정

---

BE/.gitignore
BE/package-lock.json
BE/package.json
BE/src/app.module.ts
BE/src/auth/auth.controller.ts
BE/src/auth/auth.service.ts
BE/src/auth/dto/create-auth.dto.ts
BE/src/auth/dto/update-auth.dto.ts
BE/src/auth/entities/auth.entity.ts
BE/src/database/database.module.ts
BE/src/database/database.providers.ts
BE/src/postings/dto/create-posting.dto.ts
BE/src/postings/dto/search-posting.dto.ts
BE/src/postings/entities/liked.entity.ts
BE/src/postings/entities/posting.entity.ts
BE/src/postings/entities/report.entity.ts
BE/src/timelines/dto/create-timeline.dto.ts
BE/src/timelines/entities/timeline.entity.ts
BE/src/users/dto/check-duplicated-name-response.dto.ts
BE/src/users/dto/create-user.dto.ts
BE/src/users/dto/update-user.dto.ts
BE/src/users/entities/user.entity.ts
BE/src/users/users.controller.ts
BE/src/users/users.service.ts

🌱 작업한 브랜치
- feature/#10
- TypeORM 연동
- Entity 생성
- DTO 생성
- 없음
- close #10
- close #11
- close #12

[feat] TypeORM 연동 및 Entity, DTO 생성

---

iOS/traveline/Sources/Core/Extension/UIView+.swift
iOS/traveline/Sources/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/HomeFeature/HomeScene/View/HomeListView.swift
iOS/traveline/Sources/HomeFeature/HomeScene/View/TLSearchController.swift

🌱 작업한 브랜치
- feature/#19
- 홈 검색바 UI 구현
UISearchController를 사용해서 구현했습니다 ~!
내부에서 제공하는 프로토콜을 통해 검색중, 검색결과 시점을 받아와 해당 작업을 수행할 수 있습니다.
```Swift
extension HomeVC: UISearchResultsUpdating {
func updateSearchResults(for searchController: UISearchController) {
// 검색어 입력중 - 최근검색어 및 자동완성어
}
}
```
``` Swift
extension HomeVC: UISearchBarDelegate {
func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
// 리턴키 눌렀을 경우 - 검색결과
}
}
```
placeholder만 init시점에 넘겨주도록 했습니다.
``` Swift
private let searchController = TLSearchController.init(placeholder: Constants.searchTravel)
```
https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/95872ef2-4420-41a7-ad5d-109f97445297
- Resolved: #19

[feat] 홈 검색바 UI 구현

---

BE/src/app.controller.ts
BE/src/app.module.ts
BE/src/storage/storage.module.ts
BE/src/storage/storage.service.ts

🌱 작업한 브랜치
- feature/#31
- ObjectStorage 연동
- https://guide.ncloud-docs.com/docs/storage-storage-8-4
- close: #31

[add] Nest와 ObjectStorage 연동

---

iOS/traveline/Sources/DesignSystem/Component/TLAlertController.swift

알럿창 생성에 사용할 TLAlertController 작성
🌱 작업한 브랜치
- feature/#35
- TLAlertController 생성 시, 배경색 및, 폰트 자동 설정 알림창 생성
- addAction시 style에 따라 버튼 색상 지정
- UIAlertAction은 폰트가 제대로 커스텀되지않는 문제가 있습니다..
- [노션 정리](https://spiky-rat-16e.notion.site/UIAlertController-6fab9cfcbbca4339b9b107d553679d85?pvs=4)
- 아래 스크린샷은 사용 예시에 대한 스크린샷입니다.
<details><summary>사용 예시 코드</summary> 
```swift
func showAlert() {
let alert = TLAlertController(
title: "여행 일정 삭제",
message: "여행 일정 삭제 시 되돌릴 수 없어요.\n정말 삭제하시겠어요?",
preferredStyle: .alert
)
alert.addActions([
UIAlertAction(
title: "취소",
style: .cancel,
handler: {_ in
// cancel...
}),
UIAlertAction(
title: "삭제",
style: .destructive,
handler: {_ in
// destruct...
})
])
present(alert, animated: true, completion: nil)
}
```
</details>
|기능|스크린샷|
|:--:|:--:|
|알럿창 생성 예시 - 여행 일정 삭제 |<image …

[feat] TLAlertController 작성

---

BE/src/app.controller.ts
BE/src/storage/storage.service.ts

🌱 작업한 브랜치
- feature/#51
- `Storage Service`의 `upload` 함수에서 이미지를 저장할 경로를 입력 받고, 이미지 위치(key)를 리턴하도록 수정
- `Storage Service`에 key를 이용하여 이미지 URL을 받아오는 `getImageUrl` 함수 추가
- `app.controller.ts`에 테스트용으로 작성해둔 코드도 혹시 몰라서 같이 수정하긴 했습니다...😅
- close #51

[refactor] Storage Service 함수 수정

---

BE/Dockerfile

🌱 작업한 브랜치
- feature/#64
- Dockerfile 생성
- close #64

[add] Dockerfile 생성

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- GitHub Actions 작성
- close #66

test: #66 github actions 테스트

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- CI/CD 배포를 위해 GitHub Actions 스크립트를 작성했다.
- close #
66

[add] GitHub Actions 스크립트 작성

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- runs-on 수정
- close #66

[add] github actions 스크립트 작성2

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- Docker 빌드 위치 변경: ./BE -> .
- close #66

[test] GitHub Actions 스크립트 작성3

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- 경로 문제 때문에 빌드 실패한다고 판단 => pwd, ls 명령어 추가
- close #66

[test] GitHub Actions 테스트용 pwd, ls 추가

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] install package에서 테스트용 pwd, ls 추가

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] Build Docker에 cd BE 추가

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] GitHub Actions docker 관련 이런저런 이름 변경

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] GitHub Actions에서 SSH 접속 포트 설정 추가

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] GitHub Actions의 SSH Login에서 이름 변경

---

.github/workflows/test.yml
BE/.dockerignore

🌱 작업한 브랜치
- feature/#66
- close #66

[test] GitHub Actions 옵션명 변경 & dockerignore 파일 생성

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#66
- close #66

[test] GitHub Actions의 SSH Login에서 오타 수정!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

---

.github/workflows/test.yml
BE/package-lock.json
BE/package.json

🌱 작업한 브랜치
- feature/#66
- 누락된 uuid 모듈 설치 명시
- traveline-repo에서 traveline-container로 변경
- 외부 접속 포트 1748로 변경
- close #66

[test] GitHub Actions 최종 수정

---

BE/package-lock.json
BE/package.json
BE/src/auth/auth.controller.ts
BE/src/auth/auth.module.ts
BE/src/auth/auth.service.ts
BE/src/auth/dto/create-auth.dto.ts

🌱 작업한 브랜치
- feature/#93
- JWT guard 작업을 위해 JWT 발급 작업만 먼저 진행하였다.
왜인지 환경변수 사용이 안되는 듯 해서 일단은... string으로 secret 값을 넣어두었는데 추후 수정해볼게요 😢 
|기능|스크린샷|
|:--:|:--:|
|요청 결과| ![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/138637345/c0e062cd-aab4-423b-85a4-be97bf65b6de)|
- close #93

[feat] 로그인 시 JWT 발급 일부 구현

---

BE/src/app.module.ts
BE/src/auth/auth.module.ts
BE/src/auth/auth.service.ts

🌱 작업한 브랜치
- feature/#101
환경변수를 불러오지 못하는 문제를 해결하였다.
`auth` 모듈에서 `import` 하던 `JWT` 모듈을 `app`모듈에서 `import` 하도록 변경하여 해결
- close #101

[fix] JWT 모듈 환경변수 문제 해결 (+리뷰 반영)

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#103
`Dockerfile`의 컨테이너 실행 명령어에 `-e JWT_SECRET=${{ secrets.JWT_SECRET }}` 추가 및 github secret에 환경변수 추가
- close #103

[refactor] 환경변수 추가로 인해 Dockerfile 내의 컨테이너 실행 명령어 수정

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#110
도커파일 포트를 github secret에 넣어 사용하도록 변경
- close #110

[test] 도커파일 포트 값 변경 (github secret 사용)

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#110
이전 PR에서 도커 컨테이너 실행이 되지 않는 문제가 있어서 수정사항을 되돌린다.
- close #110

[test] 포트 하드코딩 변경

---

.github/workflows/test.yml

🌱 작업한 브랜치
- feature/#110
- 이전 PR의 문제가 하드코딩 여부에 있지 않았다는 사실을 깨닫고 다시 github secret을 이용해보도록 변경
- close #110

[test] 다시 github secret으로 변경

---

BE/src/users/entities/user.entity.ts

🌱 작업한 브랜치
- feature/#94
- 컬럼명 type → socialType으로 수정
- close #94

[fix] user 컬럼명 type → socialType으로 수정

---

BE/src/auth/auth.guard.ts
BE/src/auth/auth.providers.ts
BE/src/timelines/timelines.controller.ts
BE/src/users/entities/user.entity.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/users/users.providers.ts
BE/src/users/users.repository.ts

🌱 작업한 브랜치
- feature/#106
- JWT 가드 작성
- 일부 API에 가드 적용
- 컨벤션 따라 변수명 수정
|기능|스크린샷|
|:--:|:--:|
|가드 적용 후 토큰 제시 했을 때 응답|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/138637345/52a2f871-25b3-4d8c-932d-93a17f2795bc)|
- close #106

[feat] JWT 가드 작성

---

BE/src/users/dto/user-name.dto.ts
BE/src/users/users.controller.ts
BE/src/users/users.service.ts

🌱 작업한 브랜치
- feature/#135
swagger에 API 설명을 추가하기 위해 코드를 수정하였다.
- close #135

[docs] swagger를 위한 코드 수정

---

BE/src/postings/postings.controller.ts
BE/src/swagger/swagger.setting.ts

🌱 작업한 브랜치
- feature/#135-swagger
- swagger에 authorization 추가
- 컨트롤러의 TODO (JWT에서 id 꺼내기) 수행
- Resolved: #135

[docs] swgger 일부 수정

---

BE/src/app.controller.ts
BE/src/app.service.ts

🌱 작업한 브랜치
- be-feature/#140-ipa
- manifest.plist 다운로드 페이지 생성
|기능|스크린샷|
|:--:|:--:|
|다운로드 페이지|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/6223de39-361f-4888-b504-70991e823d3e)|
- Close #140

[feat] manifest.plist 다운로드 생성

---

BE/src/app.controller.ts

🌱 작업한 브랜치
- feature/#
- Resolved: #

[fix] href 수정

---

BE/src/app.controller.ts
BE/src/app.service.ts

🌱 작업한 브랜치
- be-feature/#140-ipa
- iOS 분들이 전달해주신 메인 페이지 수정~
- 글씨가 짱 커졌어요~!
|기능|스크린샷|
|:--:|:--:|
|메인 페이지|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/ff7a938a-125f-420b-bab7-ce0b3bb9fe21)|
- Close: #140

[refactor] 다운로드 html 수정

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineTravelInfo.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/MyPostListScene/VC/MyPostListVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineDateHeaderView.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TravelInfoCVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift

- 타임라인 화면의 View Model 구현
🌱 작업한 브랜치
- feature/#137
- 타임라인 화면에서 있을 수 있는 action에 대한 흐름을 우선 연결해뒀습니다!
1. 타임라인에 진입해서 데이터를 불러와야할 때
2. 날짜를 바꿨을 때
3. 좋아요 버튼 눌렀을 때
- 그리고 해당 타임라인이 본인 것인지 아닌지에 따라 우측 상단 버튼과 플로팅 버튼 노출 처리를 연결해뒀습니다~!
- 날짜 데이터 연결까지 해두려고 계속 작업중이었는데, 
결국 이 부분은 서버에서 타임라인에 대한 정보를 받아왔을 때 출발 날짜와 도착 날짜에서 날짜와 요일을 계산하는 로직이 필요할 것 같고 이 로직은 다른 레이어에 있을 수도 있을 것 같아 덜어내고 일단 날짜 변경하는 액션까지만 연결해뒀습니다!
- 현재 Diffable DataSource를 적용하지 못해서 데이터가 변할때 전체를 reload해주고 있는데, Diffable 적용해서 수정이 필요할 것 같습니다,,
HomeVC와 MyPostListVC에서 TimelineVC 생성 시에 viewModel을 추가해뒀습니다!
|본인 게시글|타인 게시글|
|:--:|:--:|
|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/d94cd31b-a144-46f7-95e1-7bf2adf56e84" width="300">|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/154a370f-abdd-49d0-b4bb-adbcf …

[feat] 타임라인 화면 View Model 구현

---

iOS/traveline/Sources/App/RootContainerVC.swift
iOS/traveline/Sources/Domain/Model/Profile.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/VC/SideMenuVC.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/View/ProfileLabel.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/ViewModel/SideMenuViewModel.swift

사이드바 뷰모델 작업을 했어요.
🌱 작업한 브랜치
- feature/#175
사이드바 뷰모델 작업
프로필 정보를 불러오는 뷰모델말고는 다른 액션은 없는 것 같습니다.
현재는 프로필 로드하는 로직대신 임의의 프로필을 넣어줬습니다.
<image src=https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/3a65e980-d941-40e4-b8f4-bc00bc0a26de width=250>
- Resolved: #175

[feat] 사이드바 뷰모델 

---

BE/src/postings/posting.swagger.ts
BE/src/postings/postings.controller.ts
BE/src/postings/repositories/postings.repository.ts

🌱 작업한 브랜치
- be-feature/#223-feedback
- 게시글 검색 시 내가 작성한 게 나오지 않아요 => `해결` offset, limit 재설정
- 게시글 POST 시 반환 값은 id만 필요 => `수정 완료` id만 반환함
- Resolved: #223

[fix] 게시글 검색 이슈 & POST 반환 값 수정

---

BE/src/postings/postings.controller.ts

🌱 작업한 브랜치
- be-feature/#248-days
- 게시글 세부 GET API의 반환 값 중 days의 형식 변경: `5화` → `05 화`
|기능|스크린샷|
|:--:|:--:|
|days 형식|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/b23a756d-417f-48cf-9378-955f0d328cf9)|
- Close: #248

[refactor] createDaysList의 반환 형식 변경 5화 → 05 화

---

iOS/traveline/Sources/App/RootContainerVC.swift
iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Domain/UseCase/SideMenuUseCase.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/ViewModel/SideMenuViewModel.swift

사이드 바 Data-Domain Flow를 작성했어요.
🌱 작업한 브랜치
- feature/#245
사이드 바에 대한 Data-Domain 플로우를 작성했어요.
- 이미 사용중인 Repository를 활용해서 기타 특이사항은 없는 것 같습니다!
- API 연결을 아직 안해서 우선 목업을 넣어줬습니다.
- 스크린샷 변동 내용은 없어서 첨부하지 않았습니다!
- Resolved: #245

[feat] 사이드 바 Data-Domain Flow

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Core/Enum/FilterType.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Repository/Mock/PostingRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/PostingRepositoryImpl.swift
iOS/traveline/Sources/DesignSystem/View/TLFilter/TLFilterDetailButton.swift
iOS/traveline/Sources/DesignSystem/View/TLFilter/TLFilterListView.swift
iOS/traveline/Sources/Domain/Model/Filter/DetailFilter.swift
iOS/traveline/Sources/Domain/Model/Filter/Filter.swift
iOS/traveline/Sources/Domain/Model/Filter/FilterDetail/PeriodFilter.swift
iOS/traveline/Sources/Domain/Model/Filter/FilterDetail/RegionFilter.swift
iOS/traveline/Sources/Domain/Model/Filter/FilterDetail/SeasonFilter.swift
iOS/traveline/Sources/Domain/Model/Filter/FilterDetail/SortFilter.swift
iOS/traveline/Sources/Domain/Model/Sample/FilterDetailSample.swift
iOS/traveline/Sources/Domain/Model/SearchQuery.swift
iOS/traveline/Sources/Domain/Model/TagDetail/CostTag.swift
iOS/traveline/Sources/Domain/Model/TagDetail/PeopleTag.swift
iOS/traveline/Sources/Domain/Model/TagDetail/ThemeTag.swift
iOS/traveline/Sources/Domain/Model/TagDetail/TransportationTag.swift
iOS/traveline/Sources/Domain/Model/TagDetail/WithTag.swift
iOS/traveline/Sources/Domain/RepositoryInterface/PostingRepository.swift
iOS/traveline/Sources/Domain/UseCase/HomeUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeAction.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeSideEffect.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeState.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift

🌱 작업한 브랜치
- feature/#206
- 검색 간에 사용하는 `QueryParameter`를 관리하기 위해 `SearchQuery`를 생성했습니다.
- `ViewModel`에서 해당 `SearchQuery`를 관리하고 있다가, `fetchPostingList` 시에 해당 쿼리를 넘겨줘서 검색하게 됩니다!
- ~~`TLFilterListView`에서 받아온 선택된 필터 이름 `[String]`을 `DetailTag` 또는 `DetailFilter`의 `title`로 매핑 시켜서, 만들어진~~ `DetailTag`, `DetailFilter` 내에 있는 `query` 값을 가져오도록 했습니다.
- ~~해당 과정에서 enum 초기화 시 title을 통해 case를 만들어낼 수 있도록 `init?(title:)`을 추가하게 되었습니다.~~
---
> [!Important]
> 해당 부분 선택된 필터를 관리하는 방식에서 개선이 있었습니다!
> 마지막 5개 commit을 확인해주시면 될 것 같아요~!~!
- 기존에 `TLFilterListView`에서 선택된 필터를 Filter 구조체 내부에 `[String]`으로 전달하고 있었는데, `DetailFilter` 라는 친구를 하나 더 만들고, `TLFilterDetailButton`에서도 이친구를 가지고 있게 했습니다!!
- 이렇게 함으로써 어제 작업에서 다시 `String`으로 `DetailTag` 또는 `DetailFilter`을 만들어주는 코드가 필요없게 되었어요 :)
- `SearchQuery`도 기존에 필드를 다 가지고 있던 것에서 선택된 필터 리스트 …

[feat] 검색 결과 Data-Domain 구현

---

BE/src/app.controller.ts
BE/src/auth/auth.service.ts
BE/src/auth/dto/create-auth-request.dto.ts

🌱 작업한 브랜치
- feature/#280
iOS 분들 요청에 따라 이메일 값을 옵셔널로 변경했습니다!
- close #280

[refactor] 이메일 값 옵셔널 설정

---

iOS/traveline/Sources/Core/Constant/KeychainList.swift
iOS/traveline/Sources/Data/Network/API/AuthEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/LoginRequestDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/LoginResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/withdrawRequestDTO.swift
iOS/traveline/Sources/Data/Repository/AuthRepositoryImpl.swift
iOS/traveline/Sources/Domain/RepositoryInterface/AuthRepository.swift
iOS/traveline/Sources/Domain/UseCase/SettingUseCase.swift
iOS/traveline/Sources/Feature/LoginFeature/ViewModel/LoginViewModel.swift
iOS/traveline/Sources/Feature/MyPageFeature/SettingScene/ViewModel/SettingVeiwModel.swift

- feature/#284 브랜치 휴먼에러로 날려먹고 다시 PR 날립니다!
🌱 작업한 브랜치
- feature/#266
#284 코드리뷰 내용 반영
머지하면서 다른 분 작업이 올라와야하는데 밑에 깔리게 된 것 같습니다.
그래서 작업중인 브랜치에서 리셋을 했습니다.
리셋해서 이전 커밋으로는 갔는데 저녀석이 생겨서 풀 땡기면 제자리 걸음이라..
브랜치를 부득이하게 새로 팠습니다..
- Resolved: #266

[feat] 세팅화면 데이터 레이어 로직

---

BE/src/auth/auth.service.ts

🌱 작업한 브랜치
- feature/#294
bannedIp가 null인 상황 예외 처리
- close #294

[fix] iOS 요청사항 해결 - bannedIp가 null인 상황 예외 처리

---

BE/src/postings/postings.service.ts
BE/src/postings/repositories/postings.repository.ts

iOS 요청
🌱 작업한 브랜치
- be-feature/#296-add-likeds-reports
- 레포지터리의 `findAllByWriter` 메서드에 좋아요/신고 개수 반환하는 COUNT 쿼리문 추가
- `getRawMany()` 반환 값을 Posting 형식으로 변형하는 공통 메서드 생성
- Close: #296

[refactor] 내 게시글 반환 시 좋아요 수, 신고 수 필드 추가

---

BE/src/timelines/timelines.controller.ts

🌱 작업한 브랜치
- feature/#302
기존 2MB -> 10MB 조정
급한 이슈인 듯 해서 임시로 영인님께 리뷰 요청 했습니당
- close #302

[fix] iOS 요청사항 해결 - 사진 파일 용량 10MB로 조정

---

BE/src/app.service.ts

🌱 작업한 브랜치
- be-feature/#339-ipa
- Resolved: #

[chore] ipa 배포

---

BE/src/timelines/timelines.swagger.ts

🌱 작업한 브랜치
- be-feature/#350-isOwner
- swagger 예제 수정
- Resolved: #

[docs] swagger 예제 수정

---

README.md

🌱 작업한 브랜치
- feature/#361
- MVVM + CleanArchitecture
- Combine
- Swift Concurrency
- MapKit
- Keychain
잠깐 글 작성하면서 봤는데 MapKit을 활용하면 클러스터링을 쉽게 할 수 있다..?는 것 같더라구요!
만약에 쉽게 가능하다면 그런 부분도 MapKit 기술스택 설명에 추가해도 좋을 것 같긴합니당
일단 내용들 빠르게 추가해둬야할 것 같아서 생각나는대로 적어봤어요!
자유롭게 의견 주시고 첨삭하면 좋을 것 같습니닷
- Resolved: #361

[docs] README - iOS 기술스택

---

README.md

🌱 작업한 브랜치
- be-feature/#359-readme
-  프로젝트 구조 이미지 첨부
-  BE 기술 스택 작성 (키워드만이라도)
-  우리의 도전들 링크 달기
- Resolved: #359

[docs] README에 BE 내용 추가

---

BE/src/users/dto/user-info.dto.ts
BE/src/users/users.service.ts
BE/src/users/users.swagger.ts

🌱 작업한 브랜치
- feature/#364
프로필 수정, 삭제 시 프로필 이미지와 함께 경로도 반환하도록 수정하였습니다.
- close #364

[chore] 이미지 URL과 함께 경로도 같이 반환하도록 수정

---

README.md

🌱 작업한 브랜치
- be-feature/#359-be-readme
- Resolved: #

[docs] BE 기술 스택 내용 추가

---

BE/src/app.controller.ts
BE/src/auth/auth.controller.ts
BE/src/auth/auth.service.ts

🌱 작업한 브랜치
- feature/#390
- 이메일 서비스는 그대로 두되 메일을 발송하는 부분은 주석 처리 했습니다.
- IP 주소 받아오는 부분도 수정이 필요해서 같이 주석 처리 했습니다.
- 주석 처리된 코드는 추후 수정하거나 발전시켜서 개선해볼 수 있지 않을까 하는 생각에... 일단은 그대로 뒀습니다 하하
- 생각해보니... refactor 보단 chore 같긴 한데......... 이미 push해서 그냥 올립니다.... 😢
- 주석 처리한 게 전부라 리뷰는 건너뛰셔도 괜찮아요! 그냥 어떤 거 주석 처리 되었는지 정도만 보셔도 괜찮을 것 같아용 ㅎㅎ
- Resolved: #390

[refactor] IP, 이메일 관련 기능 전부 주석 처리

---

iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/Environment.swift

인증서 변경에 따른 번들 아이디 수정
🌱 작업한 브랜치
- feature/#382
인증서 변경 작업에 따른 번들 아이디 수정
디코에 필요한 것들 정리해두었고,
일단은 수동 배포를 진행할 예정이기 때문에 파일들도 전부 디코에 공유했습니다.
다운 받아서 인증서 등록해주시고 안되는 부분 있으면 공유해주세요 :)
- Development 등록
- AppStore 등록
- Config 업데이트
com.boostcamp8.traveline 으로 변경해두었는데 다른 의견있으면 언제든 환영입니다 ~
- Resolved: #382

[feat] 인증서 변경 작업

---

.github/workflows/deploy-test.yml
.github/workflows/deploy.yml

🌱 작업한 브랜치
- be-feature/#404-github-action
- deploy-test.yml
- docker account 이름 변경
- taveline → traveline으로 수정
- deploy.yml
- main 브랜치로의 push일 때만 실행되도록 수정 
- Close: #404

[fix] github action 스크립트 수정

---

iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlist.swift
iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Data/Network/Base/EndPoint.swift

🌱 작업한 브랜치
- feature/#413
테스트용 서버 추가
전처리문 추가해둬서 기기 실행시 dev, 아카이브시 prod 서버로 연결됩니다 ~ !
Config 파일 바껴서 다시 공유할게요 !
- Resolved: #413

[Feat] 테스트용 서버 추가

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Feature/MyPageFeature/SettingScene/VC/SettingVC.swift

🌱 작업한 브랜치
- feature/#395
- 설정 문서 작성 (이용약관, 개인정보 처리방침, 오픈소스 라이선스)
- 터치 영역 수정
- 노션에 작성해뒀어요 ! 
- 이용약관은 Settings.bundle 사옹해보려고 했는데 tuist로 도저히 안되더라고요 . . 해결하실 분 있으시면 환영입니다. ㅎㅎ
- 기존에 글자만 터치되던걸 해당 row를 선택하면 넘어가도록 수정했어요.
- stackView 너비랑 button의 textAlignment로 구현해뒀습니다 ~
*** 해당 branch 머지 되면 main으로 머지하겠습니다 ***
- Resolved: #395

[feat] 설정 문서 작성 및 링크 연결

---

README.md

🌱 작업한 브랜치
- be-feature/#440-readme
- BE 프로젝트 구조 이미지 변경
- 트랜잭션 시 이미지 작업과 관련된 WIKI 링크 추가
- Resolved: #440

[docs] 아키텍처 이미지 변경 & WIKI 링크 추가

---

iOS/traveline/Sources/Data/Network/API/AuthEndPoint.swift

apple 문구 추가
🌱 작업한 브랜치
- feature/#444
apple login endpoint 수정했습니다.
- apple 문구 추가
hotfix 사항이라 ios-main에 머지할게요 ~
저희 리팩토링 마무리되면 pull 받아서 씽크 맞추면 좋을 것 같습니다 : )
- Resolved: #444

[hotfix] apple login endpoint 수정

---

.github/workflows/deploy.yml

🌱 작업한 브랜치
- be-devleop
서버 마이그레이션을 위해 secret 값을 업데이트 하였습니다.
- Resolved: #

[chore] 서버 마이그레이션 - Actions의 secret 수정

---

BE/Dockerfile

🌱 작업한 브랜치
- feature/#
- Resolved: #

[chore] Dockerfile 수정

---

.github/workflows/deploy.yml

🌱 작업한 브랜치
- feature/#
- Resolved: #

[fix] update deploy.yml

---

BE/src/app.module.ts
BE/src/app.service.ts
BE/src/auth/auth.module.ts
BE/src/file/file.module.ts
BE/src/file/file.service.ts
BE/src/postings/postings.module.ts
BE/src/postings/postings.service.ts
BE/src/timelines/timelines.module.ts
BE/src/timelines/timelines.service.ts
BE/src/users/users.module.ts
BE/src/users/users.service.ts

🌱 작업한 브랜치
- be-feautre/#468-change-attaching-files
- FileModule/FileService 생성
- 기존에 StorageModule/StorageService 사용하던 곳에서 FileModuel/FileService 사용하도록 정
- 기존 StorageModule/StorageService 파일을 남겨 두었습니다. 나중에 활용할 수도 있으니!
- Resolved: #468

[feat] 파일 시스템으로 이미지를 관리하도록 하는 서비스 생성

---

BE/Dockerfile

🌱 작업한 브랜치
- be-feature/#474-docker-base-img
- 도커 베이스 이미지를 알파인 이미지로 변경합니다.
- 1G -> 400Mb 정도로 이미지 크기를 줄였습니다.
- Resolved: #474

[fix] Docker base img 수정

---

.github/workflows/deploy.yml

🌱 작업한 브랜치
- be-feature/#475-yml-synchronization
- main의 deploy.yml 복붙
- Resolved: #475

[fix] 배포 yml 파일 동기화

---

BE/Dockerfile

Reverts boostcampwm2023/iOS07-traveline#476

Revert "[fix] Docker base img 수정"

---

BE/Dockerfile

🌱 작업한 브랜치
- feature/#
- Resolved: #

[fix] Docker base img 수정 (develop으로...)
