iOS/traveline/Resources/Colors.xcassets/DarkGray.colorset/Contents.json
iOS/traveline/Resources/Colors.xcassets/DisabledGray.colorset/Contents.json
iOS/traveline/Sources/Core/Extension/String+.swift
iOS/traveline/Sources/Core/Extension/UIView+.swift
iOS/traveline/Sources/Data/Network/Base/NetworkError.swift
iOS/traveline/Sources/DesignSystem/Component/TLLabel.swift
iOS/traveline/Sources/DesignSystem/Component/TLTag/TLTag.swift
iOS/traveline/Sources/DesignSystem/Component/TLTag/TLTagStyle.swift
iOS/traveline/Sources/DesignSystem/TLColor.swift

- 재사용 가능한 `TLTag` 구현
- Extension 추가
- darkGray, disabledGray 추가
- TLLabel 수정
🌱 작업한 브랜치
- ios-feature/#20-TravelineTag
~~~swift
let selectableTag = TLTag(
style: .selectable,
name: "선택 가능",
color: TLColor.Tag.period
)
~~~
- 위와 같은 방법으로 Tag를 생성할 수 있습니다. 🙂
- **Style**은 아래 사진 순서대로 `normal`, `cancellable`, `selectable` 3가지가 있어요!
- `selectable` 태그에서는 `isSelected` 프로퍼티를 토글하면 border와 그림자가 적용됩니다.
- 피그마의 형식에 맞추어 그림자를 추가할 수 있도록 UIView+ Extension을 추가했습니다. 아래와 같이 사용하면 됩니다 😉
- 태그에서는 있던 그림자를 제거해야할 소요가 있었는데요, 그래서 `removeShadow()`도 UIView+에 구현해두었습니다!
~~~swift
innerView.addShadow(
xOffset: 0,
yOffset: 4,
blur: 4,
color: TLColor.black,
alpha: 0.25
)
innerView.removeShadow()
~~~
- `spread`는 기본값 0으로 넣어뒀고, 수정이 필요하면 필드에서 추가해 호출하시면 됩니당
- `TLLabel`을 사용하면서, text 값이 변경되는 경우를 처리해줘야겠다는 생각이 들어 색상과 함께 외부에서 변경할 수 있는 …

[feat] TLTag 구현

---

BE/src/app.controller.ts
BE/src/app.module.ts
BE/src/auth/auth.module.ts
BE/src/storage/storage.module.ts
BE/src/storage/storage.service.ts
BE/src/users/entities/user.entity.ts
BE/src/users/users.controller.ts
BE/src/users/users.module.ts
BE/src/users/users.providers.ts
BE/src/users/users.repository.ts
BE/src/users/users.service.ts

🌱 작업한 브랜치
- feature/#27
- GET `users/:id` : 사용자의 프로필 사진과 닉네임 정보를 가져온다.
- PUT `users/:id` : 사용자의 프로필 사진 또는 닉네임을 수정한다.
- GET `users/duplicate/check`: 닉네임 변경 전에 중복 여부를 검사한다.
- 원래 닉네임 중복 체크 API는 GET `users/duplicate`였으나 GET `users/:id`와 충돌하는 문제가 있어 (duplicate를 id값의 일종으로 인식해버림) 임시로 GET `users/duplicate/check`로 수정해두었습니다! 혹시 더 괜찮은 URI가 있다면 리뷰로 남겨주세요 😄 
- `Storage Module`관련해서 아침에 말씀드린 건 다른 pr로 따로 뺄까 싶어서 이 pr에는 커밋 안했어요!
- close #27

[feat] users API 구현

---

iOS/traveline/Sources/Feature/MyPageFeature/SettingScene/VC/SettingVC.swift

🌱 작업한 브랜치
- feature/#49
세팅 뷰 UI를 구현.
서비스 지침 관련 웹뷰 링크 연결.
로그아웃이나 탈퇴 시 알람창 UI 연결.
서비스 지침 관련은 추후에 작성이 되면 노션이나 다른 링크를 통해 웹뷰로 연결할 예정이라 지금은 임시로 다른 웹페이지를 넣어두었습니다.
접근할 수 없는 url은 런타임에러가 발생해서 웹뷰 연결을 막아두었습니다.
|기능|스크린샷|
|:--:|:--:|
|세팅 뷰 UI|<image src=https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/bae49c54-fa57-4130-9b6c-e8a51618e2fd width=300>| 
- Resolved: #49

[feat] 세팅 뷰 UI 작성

---

BE/src/postings/entities/liked.entity.ts
BE/src/postings/entities/posting.entity.ts
BE/src/postings/entities/report.entity.ts

좋아요 직접 삭제 시엔 soft delete로, 회원 탈퇴나 게시글 삭제 시엔 좋아요 hard delete로 설정했다.
🌱 작업한 브랜치
- be-feature/#56-add-column
- 좋아요에 is_deleted 필드 추가 (좋아요 취소 시 soft delete)
- 회원/게시글 삭제 시 좋아요/신고 기록도 삭제되도록 설정
- MySQL에서 onUpdate의 디폴트가 `CASCADE`라서 그냥 지워버렸어요 ㅎㅎ 괜한 코드가 1줄 느는 것 같아서요!
- close #56

[refactor] 좋아요에 is_deleted 필드 추가, on delete/update 정책 수정

---

iOS/traveline/Sources/DesignSystem/Component/TLImageLabel.swift
iOS/traveline/Sources/Domain/Model/TimelineDetailInfo.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDtailScene/VC/TimelineDetailVC.swift

🌱 작업한 브랜치
- feature/#79
- 재사용 이미지라벨 작성
- 타임라인 상세 뷰 UI 작성
- 재사용 이미지라벨을 만들었어요. 제가 만들 다른 뷰에서도 재사용을 여러번할 것 같아서 따로 TLImageLabel로 만들었습니다.
- 스크린샷은 아래 첨부하였고, 들어가는 이미지와 텍스트를 변경할 수 있습니다.
- 타임라인 상세 뷰의 사진 이미지를 원본 비율에 맞춰서 보여지도록 했습니다. 정방형에서 크롭할껀지 정확히 확정이 안됐어서 우선 이렇게 진행했습니다. 변동 사항있으면 리뷰 남겨주세요 :)
- 타임라인 내용이 길어지면 스크롤이 가능하게 스크롤뷰로 작업했습니다.
|기능|스크린샷|
|:--:|:--:|
|재사용 이미지라벨|<image src="https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/5053ace2-730f-493e-831e-40d107c716a7" width = 100>|
|타임라인 상세 뷰 UI|<image src=https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/26ef9878-1409-4dd3-89a5-a3b963886666 width = 300>|
- Resolved: #79

[feat] 타임라인 상세 뷰 UI

---

iOS/traveline/Sources/Core/Extension/UICollectionView+.swift
iOS/traveline/Sources/DesignSystem/View/TLTagList/TLTagListView.swift
iOS/traveline/Sources/Domain/Model/TimelineSample.swift
iOS/traveline/Sources/Domain/Model/TimelineTravelInfo.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TravelInfoCVC.swift

- 타임라인 화면 중 여행 정보 UI를 먼저 구현해 적용했습니다!
🌱 작업한 브랜치
- feature/#87
- UICollectionView Extension에 셀과 헤더를 좀 더 편하게 register하고 dequeue할 수 있는 함수를 추가해뒀습니다!
아래와 같이 사용하시면 됩니당 🙂
~~~swift
collectionView.register(cell: TravelInfoCVC.self)
let cell = collectionView.dequeue(cell: TravelInfoCVC.self, for: indexPath)
~~~
- 어제 만들었던 TLTagListView에서 태그를 나중에 추가할 수 있도록 변경했습니다!
- `setTags(_:style:)` 메서드를 통해 추가할 수 있습니당
- 타임라인 화면 VC를 생성하고 여행 정보 cell을 적용해봤습니다.
- Compositional Layout을 적용했고, Diffable DataSource도 함께 적용하려고 했는데 둘 다 잘 모르는 상태에서 함께 적용하려니 너무 잘 안되더라구요 ^^,, 그래서 DataSource는 나중에 변경하도록 하겠슴다
- 태그가 늘어날 수록 여행 정보 영역이 같이 늘어날 수 있도록 dynamic height를 적용했습니당
Compositional Layout에서 section의 layout을 만들어주는 메서드를 따로 빼서 사용했는데, (`makeTravelInfoSection`)
section이 많아질수록 이 코드도 자연스럽게 많아질 것 같은데.... 어떻게 관리해야할지 고민중임다 …

[feat] 타임라인 - 여행 정보 UI 구현

---

BE/src/app.module.ts
BE/src/auth/auth.service.ts
BE/src/storage/storage.service.ts
BE/src/users/dto/user-info.dto.ts
BE/src/users/users.constants.ts
BE/src/users/users.controller.ts
BE/src/users/users.providers.ts
BE/src/users/users.repository.ts
BE/src/users/users.service.ts

🌱 작업한 브랜치
- feature/#59
- users API 엔드포인트 수정
**iOS 요청사항 반영**
- 엔드포인트에서 사용자 식별자 제거 -> jwt 안에 식별자 저장하여 사용
**BE 리뷰 반영**
- `/:id` 핸들러가 `/duplicate` 핸들러와 충돌했던 문제는 iOS 요청사항을 해결하며 함께 해결
- 프로필 사진 업로드 전 사용자 식별자를 이용한 유효성 검사 과정은 jwt 가드를 적용하였기 때문에 따로 추가하지 않음
- 프로필 사진 변경 시 기존 프로필 사진 삭제
- 변수명 저장용 `users.constants.ts` 파일 분리
- 예외 처리 방식 변경
- `storage` 모듈 수정
- users API에서 프로필 사진 변경 시 기존 프로필 사진을 삭제하기 위해 delete 함수 추가
- 기타
- DTO 이름 변경
- 개발 시 번거로움을 줄이기 위해 JWT 유효기간 9시간으로 연장
- `chore` 커밋들은 단순 이름 변경(?) 급의 간단한 커밋이니 건너뛰셔도 괜찮습니당 ㅎㅎ
- 리뷰&머지 천천히 해주셔도 괜찮습니당 ㅎㅎ
- `users.service.ts`에 예외처리 목적으로 `try catch`를 엄청 때려박았는데... 괜찮으려나요 ㅠㅠ
- DTO 이름에도 따로 컨벤션이 있나용? 같은 형태의 DTO를 여러 핸들러에서 사용해서... 하나로 통일해서 쓰고 싶어서 네이밍을 좀 더 범용성 있게(?) 바꿔봤는데 괜찮은지 궁금합니다...
- Closes #59

[refactor] users API 리뷰 및 요청사항 반영

---

iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineCardCVC.swift

🌱 작업한 브랜치
- feature/#125
- 타임라인에서 마지막 셀에 선이 보이지 않도록 처리했습니당
- 아래 사진처럼 밑에 선이 보이는 부분까지 한 셀로 처리해서, 마지막 셀일때는 해당 선의 길이를 조절해줬어용
- Resolved: #125

[feat] 타임라인 마지막 셀 처리

---

iOS/traveline/Sources/Core/Enum/TravelRegion.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/View/Cell/RegionCVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/View/RegionBottomSheetVC.swift

🌱 작업한 브랜치
- feature/#127
- 여행 생성 화면에서 지역 선택 -> 바텀시트 부분을 구현했습니다.
- 지역 목록은 일단 Enum에 추가해두었습니다!
셀 선택 시에 Highlight 색상을 임의로 줘봤는데 괜찮은가용? 🤔
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/9c7ead5d-45f8-4f7c-a828-a2447909379b
- Resolved: #127

[feat] 지역 선택 바텀시트 구현

---

BE/src/database/database.providers.ts
BE/src/postings/entities/mappings/posting-mapping.entity.ts
BE/src/postings/entities/mappings/posting-theme.entity.ts
BE/src/postings/entities/mappings/posting-with-who.entity.ts
BE/src/postings/entities/tags/theme.entity.ts
BE/src/postings/entities/tags/with-who.entity.ts
BE/src/postings/postings.controller.ts
BE/src/postings/postings.module.ts
BE/src/postings/postings.service.ts
BE/src/postings/repositories/likeds.repository.ts
BE/src/postings/repositories/mappings/posting-mapping.repository.ts
BE/src/postings/repositories/mappings/posting-themes.repository.ts
BE/src/postings/repositories/mappings/posting-with-whos.repository.ts
BE/src/postings/repositories/postings.repository.ts
BE/src/postings/repositories/reports.repository.ts
BE/src/postings/repositories/tags/tag.repository.ts

🌱 작업한 브랜치
- be-feature/#85-update-posting
- 태그처럼 게시글과 테마/누구랑 매핑 엔티티/레포지터리도 부모 클래스를 상속 받도록 수정했습니다.
- id에 해당하는 게시글 조회/수정/삭제 API를 수정했습니다.
- 좋아요 토글 API와 신고 API를 수정했습니다.
- 엔티티 파일이 수정됐습니다! database 모듈의 synchronize 속성을 false로 만들었기 때문에 서버에서 직접 DB를 생성하든가 해야 할 것 같습니다!!
- 게시글의 누적 신고 수가 5를 초과하면 차단되도록 했는데요. 일단 임시로 넣은 수라서 더 적절한 기준 값이 있으면 편하게 말씀해주세요 😊
- Close #85

[refactor] DB 구조 변경에 따른 기존 게시글 조회/수정/삭제 및 좋아요, 신고 API 수정

---

iOS/traveline/Sources/Core/Cache/ImageCacheRepository.swift
iOS/traveline/Sources/Core/Cache/TLImageCache.swift
iOS/traveline/Sources/Core/Cache/TLImageDownloader.swift
iOS/traveline/Sources/Core/Extension/UIImageView+.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineSample.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineCardCVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineCardView.swift

> 이미지 캐싱 구현
🌱 작업한 브랜치
- feature/#129
- 이미지 캐싱 또한 저장소로 볼 수 있지 않을까..? 라는 생각에 Repository를 통하도록 구현해봤습니다.
- `ImageCacheRepository`에서 `memoryCache`와 `fileManager`를 가지고 있습니다!
1. `UIImageView` -> `setImage`
2. `TLImageCache`에서 메모리 캐시, 디스크 캐시를 확인하고 있으면 가져옵니다.
3. 없으면 `TLImageDownloader`에서 `downloadTask`를 통해 이미지를 다운로드하고 `TLImageCache`에 저장합니다.
- cell 안에 UIImageView가 있고 재사용될 때, 이전 셀에서 요청한 downloadTask의 응답이 뒤늦게 도착해서 이미지가 여러번 변경되는 현상이 있었습니다.
- cancel 로직 구현을 위해 `TLImageDownloader`에서 downloadTask를 딕셔너리로 들고 있다가, cancelDownload 시에 해당 downloadTask를 cancel 해주었습니다!
- 이때 딕셔너리가 thread safe하지 않기 때문에 `downloadTaskQueue`를 만들고 해당 DispatchQueue에서 딕셔너리에 write 하도록 했슴다
- 현재는 단순하게 `memoryCache`의 `countLimit`을 50개로 정해두었는데, 어떤 방식으로 정책을 정하면 좋을지.. 고민해봐야 할 것 같습니닷
- 아래 영상은 countLimit을 2개로 두고 diskCache에서 가져오는 걸 테스트해본 영상입니다~! …

[feat] TLImageCache 구현

---

iOS/traveline/Sources/Core/Enum/TagType.swift
iOS/traveline/Sources/DesignSystem/Component/TLTag/TLTag.swift
iOS/traveline/Sources/DesignSystem/View/TLTagList/TLTagListView.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/View/SelectTagView.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/ViewModel/TravelViewModel.swift

> 여행 생성 화면 View Model 구현, 연결
🌱 작업한 브랜치
- feature/#136
- "테마"와 "함께" 태그만 다중 선택이 가능한 것을 확인하고 `TagType`에 `isMultiple` 프로퍼티를 추가했습니다.
- `TLTagListView`에서 태그를 선택할 때도 `TagType`에 따라 다중 선택을 구현했습니다!
- TravelViewModel을 구현하고 TravelVC에 연결했습니다.
- 현재 제목이 입력됐을 때, 지역이 선택됐을 때, 출발/도착 날짜가 선택됐을 때 Action을 보내주고 있습니다!
- 완료 버튼의 활성화 여부를 제목, 지역, 날짜의 올바른 입력 여부에 바인딩 해두었습니다.
- 완료 버튼을 눌렀을 때 선택된 Tag들을 전달하게 됩니다!
- "출발 날짜가 도착 날짜보다 빠르거나 같아야 한다"라는 조건을 위해 ViewModel에도 isValidDate라는 값을 검사하고 있지만, Date Picker의 minimumDate를 설정해 도착 날짜 선택 Date Picker는 출발 날짜 이전의 날짜를 선택할 수 없도록 해두었습니다!
선택된 태그들의 관리에 대해 고민이 있었는데요!
태그가 선택될 때마다 이걸 ViewModel로 넘겨주어 관리해야하나? 하는 고민이 있었습니다.
하지만 현재 입력받는 태그가 필수 태그가 아니고, 태그의 선택 여부에 따라 화면의 상태 (`State`)가 변하지 않는다,, 라고 느껴져서
완료 버튼을 누르게 되었을 때 선택된 태그들을 `donePressed` action과 함께 보내주게 해놨는데,
이렇게 되면 네트워크 요청을 보낼 때 어떤 데이터는 …

[feat] TravelViewModel 구현

---

iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift

🌱 작업한 브랜치
- feature/#157
- TravelViewModel 구현 이후 develop으로 merge 되었는데, 기존 develop에 존재하던 HomeVC에서 TravelVC 생성 시 viewModel 주입이 되지 않아서 에러가 발생하고 있었습니다.
- 일단 viewModel 생성자를 추가해주었는데, 어떻게 이렇게 된건지..? 파악중입니다..
TravelViewModel을 수정된 develop으로 fetch-rebase한 과정에서 해당 에러를 처리하지 않고 merge된 것 같습니다 ^^;;
죄송함니다!!! 🙇🏻
- Resolved: #157

[hotfix] HomeVC에서 TravelViewModel 주입

---

iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift
iOS/traveline/Sources/Feature/LoginFeature/VC/LoginVC.swift
iOS/traveline/Sources/Feature/LoginFeature/ViewModel/LoginViewModel.swift
iOS/traveline/traveline.entitlements

🌱 작업한 브랜치
- feature/#165
- sign with apple 설정 추가 (cc. tuist)
- 애플 로그인 구현 (cc. vc + viewmodel)
- start [애플 로그인 버튼 클릭 시]
- success [delegate로 complete 받아올 시]
- fail [delegate로 error 받아올 시]
시점을 기준으로 ViewModel을 생성했습니다 :)
sign with apple을 추가하면 entitlements가 추가되는데
Target에 해당 옵션을 추가해줘야 tuist generate할 때 같이 생성돼서 사용할 수 있습니다 :)
~~### userIdentifier, identitytoken
일단 애플 로그인을 통해 위의 두 가지를 받아오도록 했습니다.
identitytoken은 무조건 서버에 넘겨줘야하고, userIdentifier도 저번에 얘기가 나왔어서 일단은 추가했는데
추후에 서버랑 협의하고 필요없으면 제외해도 좋을 것 같습니다 !~~
→ 협의 완! userIdentifier 제외하겠습니다 !
로그인 실패하는 경우에 대한 alert창이나 toast가 필요하지 않을까 싶네요 , ,
구현하면서 서버 에러 등의 케이스가 발생할텐데 alert이나 toast로 통일하고 message만 다르게 가져가도 좋을 것 같아요 :)
https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/020aad6d-6598-4c18-b0ea-a9cc1d8068a2
- Resolved: #165

[feat] 애플 로그인 구현

---

BE/src/postings/entities/posting.entity.ts
BE/src/postings/posting.swagger.ts
BE/src/postings/postings.controller.ts
BE/src/postings/postings.service.ts
BE/src/postings/repositories/postings.repository.ts

🌱 작업한 브랜치
- be-feature/#43-new-search
- Posting 엔티티에 liked와 report 필드에 @RelationId 데코레이터가 달려 있었는데, 지웠습니다! (외래키 관계는 그대로 유지돼요!)
- 반환되는 내용 자체는 그대로고, liked → likeds, report → reports처럼 필드 이름만 복수형으로 바뀌었어요!
- @RelationId 데코레이터를 사용하면 조회할 때 굳이 liked/report 테이블을 JOIN하지 않아도, 게시글 id를 posting 필드 값으로 가지는 liked/report의 레코드를 반환해주는데요.
- 그런데 이때 반환해주는 liked/report 레코드는 TypeORM이 자동으로 반환해주는 것이기 때문에 제가 liked.isDeleted = false인 레코드만 뽑으라고 설정할 수가 없어요 ㅠㅠ
- 그래서 동일한 기능을 구현하되 제가 원하는 조건을 추가하기 위해 @RelationId를 지우고, 직접 JOIN하는 방식으로 변경했습니다.
- 만약 @RelationId 안 지우고, JOIN으로 liked.isDeleted = false 조건 추가하면 이러 식으로 반환돼요.
```
Posting {
id: '9093b3bd-2730-49fd-a783-f4fd055e3f93',
title: 'bread ❤️❤️',
...
// @RelationId로 인해 자동으로 모두 반환되는 레코드
like: [
{
user: '111',
posting: 'aaa'
},
{
user: '111',
posting: 'bbb'
},
],
// JOIN으로 직접 …
```

[refactor] Posting 엔티티에서 @RelationId 제거 (기능 변화X)

---

iOS/traveline/Sources/Core/Constant/KeychainKey.swift
iOS/traveline/Sources/Core/Util/Keychain/KeychainManager.swift
iOS/traveline/Sources/Core/Util/Keychain/KeychainWrapper.swift

🌱 작업한 브랜치
- feature/#166
- Keychain Util 구현
- KeychainKey 추가
KeychainManager에서 기본적인 키체인의 CRUD 작업을 수행합니다.
단순 디버깅용 enum 및 함수는 가장 아래 extension으로 빼뒀습니다 :)
추후에 혹시나 트래킹이 필요할 수도 있을 것 같아서요 !
PropertyWrapper를 사용해 키체인을 관리할 수 있도록 했는데요.
- 값 선언: KeychainManager.set을 호출해 값 저장
- get 접근: KeychainManager.read를 호출해 값을 가져옴
- nil 선언: KeychainManager.delete()를 호출해 값 삭제
해당 enum 내부에 사용할 키체인들 추가로 key와 함께 선언해두고 사용하면 될 것 같습니다 :)
```Swift
enum KeychainKey {
@KeychainWrapper<String>(key: "accessToken") static var accessToken
@KeychainWrapper<String>(key: "refreshToken") static var refreshToken
}
```
```Swift
KeychainKey.accessToken = "서버에서 받아온 토큰" // 저장
KeychainKey.accessToken = nil // 삭제
print(KeychainKey.accessToken) // 값 받아옴
```
- Resolved: #166

[feat] 키체인 구현

---

iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/LikedsDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingDetailResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/WriterDTO.swift
iOS/traveline/Sources/Data/Repository/TimelineRepositoryImpl.swift
iOS/traveline/Sources/Domain/RepositoryInterface/TimelineRepository.swift
iOS/traveline/Sources/Domain/UseCase/FetchTravelInfoUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/MyPostListScene/VC/MyPostListVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift

- GET Posting에 대해서 예시 플로우를 구현했습니다!
🌱 작업한 브랜치
- feature/#169
- 아침에 한 번 공유드렸었지만 흐름을 살펴보자면,
1. ViewModel에서 UseCase (Interface) 가짐
2. UseCase에서 Repository Interface 가짐
3. RepositoryImpl에서 네트워크 요청
이런 식이 될 것 같아요!
- 아침에 의견 모은대로 UseCase에서 Future-Task를 통해 async를 AnyPublisher로 흐름을 바꿔주게 해두었습니다!!
- `Data - Network - DataMapping`에 DTO를 추가해뒀습니다!
- 이번에 `GET Posting` 관련해서 DTO를 추가해봤는데, 어떤 필드가 **nullable**한 지 확인이 어렵더라구요! 그래서 전체 필드를 **optional**로 가져가야할지.. 아니면 백엔드분들한테 여쭤보는게 맞을 지 고민 중입니다
- `PostingResponseDTO`에서 태그를 Domain 형식으로 바꿔주는데 **nullable** 여부에 따라 처리가 필요할 것 같아서 일단 해당 부분 비워뒀습니다.
- 일단 `VC-ViewModel-UseCase-Repository-Network` 의 의존 관계를 한번에 만들어주기 위해서 편의를 위해 VCFactory를 추가하게 되었습니다.
- `VCFactory.makeTimelineVC()` 이렇게 호출해주시면 됩니다 :)
- 이친구 있을 위치가 애매해서 일단 `Core-Enum`에 넣어뒀어용
- 의존성 관리에 대해서 관심이 생기기 시작했습니다... 🙂 …

[feat] Data-Domain 플로우 구현

---

iOS/traveline/Sources/App/RootContainerVC.swift
iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingDetailResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/PostingRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/PostingRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Profile.swift
iOS/traveline/Sources/Domain/RepositoryInterface/PostingRepository.swift
iOS/traveline/Sources/Domain/UseCase/HomeUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeSideEffect.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/ViewModel/SideMenuViewModel.swift

- HomeUseCase 추가
🌱 작업한 브랜치
- feature/#190
- 논의 이후에 UseCase를 모든 행위당 하나가 아니라 화면 당 일대일로 생성하는 것으로 해서 `HomeUseCase`를 추가했습니다!
- 대신 `HomeUseCase` 안에 다양한 행위들이 들어가게 될 것 같아서 PR을 나누게 되었습니닷
- 행위마다 하나씩 나눠서 올릴 예정이에요!
- Posting에 관련된 서비스를 담당할 Repository를 생성했습니다!
- 여기서 서버 Posting 관련된 통신을 담당하면 될까 싶은데 괜찮을까요?? 약간 지금 느낌은 API의 큰 단위 (Postings, Users, Timelines)이런 식으로 Repository를 나누면 어떨까 싶은 느낌이 있어서요!
- 원래 JSON 자체를 Mock으로 만들까 했으나 JSON 목 데이터 만드는 작업 자체에 시간 소요가 꽤 될 것 같아서 `Repository` 자체를 Mock으로 생성해서 테스트 해줬습니다 :)
- `UseCase`와 `Repository`가 Interface를 통해 느슨하게 연결되어 있기 때문에 `UseCase`에 `Mock Repository`를 대신 주입해 간단하게 교체할 수 있었습니다 🤔
- 이렇게 작업해두면 나중에 서버를 실제로 붙일때 Repository만 마저 작업해서 갈아끼우면 될 것 같아요!!
Profile 객체의 id 필드 충돌 관련 수정사항이 있습니다 ~!
진짜 별개의 얘기긴긴 한데 화면 녹화할 때 맥북 화면 녹화할때랑 외장 모니터 화면 녹화할때랑 용량 차이가 꽤 크네요??
(모니터가 훨씬 작네용,,) …

[feat] 홈 화면 - Use Case 추가

---

iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift

타임라인 작성 화면 뷰모델을 만들었어요.
🌱 작업한 브랜치
- feature/#174
- 타임라인 작성 화면 뷰모델
- 작성 완료 시 타임라인 생성에 필요한 Day, Date, postingId는 이전 VC에서 넘겨줄 수 있게 뷰모델의 인자값으로 추가했어요.
- 사진과 장소를 입력하지않아도 제목과 내용만 입력하면 완료할 수 있도록 버튼을 활성화했어요.
https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/5aa2bc1e-44f6-47d9-b170-a6eebb186f65
- Resolved: #174

[feat] 타임라인 작성 화면 뷰모델

---

BE/src/timelines/dto/create-timeline.dto.ts
BE/src/timelines/timelines.controller.ts
BE/src/timelines/timelines.module.ts
BE/src/timelines/timelines.service.ts
BE/src/timelines/timelines.swagger.ts

🌱 작업한 브랜치
- be-feature/#184-timeline-image
-  타임라인 POST 시 File 전달 받고, Object Storage에 저장
-  타임라인 GET 시 Object Storage에서 URL을 생성하여 전달
-  타임라인 PUT 시 Object Storage에서 기존 사진 삭제 및 새 사진으로 저장
-  타임라인 DELETE 시 Object Storage에서 사진 삭제
|기능|스크린샷|
|:--:|:--:|
|POSTMAN 테스트 시 image 파라미터|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/bf408f82-4ed0-460e-8d99-66fa38a48457)|
|Swagger 테스트 시 image 파라미터|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/265c530c-bdfe-4904-97b9-2fe21cd61f2c)|
- close #184

[feat] 타임라인에서 이미지 관련 로직 추가

---

BE/src/postings/dto/create-posting.dto.ts
BE/src/postings/dto/search-posting.dto.ts
BE/src/postings/postings.controller.ts
BE/src/postings/postings.service.ts
BE/src/postings/repositories/postings.repository.ts
BE/src/timelines/timelines.repository.ts
BE/src/timelines/timelines.service.ts
BE/src/timelines/timelines.swagger.ts

🌱 작업한 브랜치
- be-feature/#185-thumbnail
- 자잘한 수정
- Swagger 관련 수정
- dto의 데코레이터 수정
- 변수 초기화 방식 변경
- 게시글에서 처음으로 생성되는 타임라인의 이미지가 썸네일로 지정됨
- Day1의 첫 번째 타임라인의 이미지가 썸네일이 아닐 수도 있음
- A 타임라인이 게시글의 썸네일인데, **A 타임라인이 `수정`될 경우**
- 먼저 타임라인 수정
- 게시글 관련 타임라인 중 1개의 이미지를 게시글 썸네일로 지정
- 반드시 수정된 A 타임라인의 이미지가 게시글의 썸네일이 아닐 수도 있음 (랜덤)
- A 타임라인의 게시글의 썸네일인데, **A 타임라인이 `삭제`될 경우**
- 먼저 타임라인 삭제
- 게시글 관련 타임라인 중 1개의 이미지를 게시글 썸네일로 지정
- 반드시 수정된 A 타임라인의 이미지가 게시글의 썸네일이 아닐 수도 있음 (랜덤)
|기능|스크린샷|
|:--:|:--:|
|request body 형식을 json에서 x-www-form-urlencoded로 변경함에 따라 ENUM을 적극 활용할 수 있게 됨!|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/dc586fe9-3a8e-4bcb-862c-86095b48d593)| 
- Close: #185

[feat] 타임라인 생성, 수정, 삭제 작업 시 게시글 썸네일 처리

---

BE/src/postings/postings.controller.ts
BE/src/timelines/dto/create-timeline.dto.ts

🌱 작업한 브랜치
- be-feature/#223-feedback
- 게시글 POST 시 request body 형식 json으로 변경
- form-data로 하면, 인원수, 이동수단 등 옵셔널 태그에 값을 넣지 않았을 때 에러가 발생할 수 있고
- 테마/누구랑 태그에서 배열을 전달할 수가 없어요ㅎㅎ...
- 타임라인 POST 시 coordX, coordY는 옵셔널인데, 이것들의 값을 전달하지 않을 때는 `Send empty value` 체크를 해지해야 한다는 안내를 넣었습니다.
- 체크한 채로 보내면 coordX, coordY는 Number여야 한다는 에러가 발생합니다.
- Close: #223

[fix] swagger 수정 (request body, 안내 메시지)

---

iOS/traveline/Sources/Core/Extension/String+.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingTitleListResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/PostingRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/PostingRepositoryImpl.swift
iOS/traveline/Sources/DesignSystem/Component/TLLabel.swift
iOS/traveline/Sources/DesignSystem/View/TLSearch/TLSearchInfoView.swift
iOS/traveline/Sources/Domain/Model/SearchKeyword.swift
iOS/traveline/Sources/Domain/RepositoryInterface/PostingRepository.swift
iOS/traveline/Sources/Domain/UseCase/HomeUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeSideEffect.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift

- 홈 화면의 연관 검색어를 가져오는 Data-Domain 플로우를 연결했습니다!
🌱 작업한 브랜치
- feature/#205
- 검색어와 일치하는 결과 부분에만 색상 처리를 추가해주기 위해 `String+ Extension`에 문자열의 일치하는 부분 `range`를 계산해주는 `findCommonPrefixRange(_ compareString: String)` 메서드를 추가했습니다!
- 추가로 `TLLabel`에서 기존 font 설정은 유지한채로 해당 범위의 색상만 변경해주기 위해 `setColor(to color: UIColor, range: NSRange)` 메서드도 추가했어요!
~~~ swift 
titleLabel.setColor(
to: TLColor.main,
range: "일치 부분 찾고싶은 문자열".findCommonPrefixRange("비교할 문자열")
)
~~~
- 요런식으로 사용하시면 됩니다 ㅎ (장소 검색에서도 동일하게 사용하시면 될 것 같아요!)
- 검색어를 다 지웠을 때는 다시 검색 기록이 노출되도록 하는 로직을 `searching` action 쪽으로 옮겼습니다!
- searching -> fetchRelatedKeyword -> 여기서 keyword가 없다면 fetchRecentKeyword 방출, 없으면 fetchRelatedKeyword 방출 이렇게 흘러갑니다!
검색 화면에서 여전히 [+] 버튼 노출되는 문제가 있었는데, `showHome`에서 `homeViewType`을 바꿔주는데 `showHomeList`에서도 `homeViewType`을 중복해서 바꾸고 있어서 …

[feat] 연관 검색어 Data-Domain 연결

---

BE/src/users/dto/update-user.dto.ts
BE/src/users/users.controller.ts

🌱 작업한 브랜치
- feature/#240
swagger 데코레이터를 수정해서 이제 users API에서도 스웨거를 통한 사진 전송이 가능합니다!
|기능|스크린샷|
|:--:|:--:|
|사진 전송 가능!|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/138637345/00c1bdc8-b98b-4b53-a7cc-bcd7d7d5d021)|
- close #240

[docs] swagger에서 사진 전송 가능하도록 변경

---

BE/package-lock.json
BE/package.json
BE/src/database/database.providers.ts
BE/src/main.ts
BE/src/timelines/timelines.service.ts

🌱 작업한 브랜치
- be-feature/#215-transaction
- timeline service에서 `create`, `update`, `delete` 메서드에 트랜잭션 적용
- 만약 사진을 오브젝트에 스토리지에 저장하고, 새로운 이미지 경로로 타임라인을 update한 다음에, 게시글의 썸네일을 update 과정에서 에러가 난다면
- 타임라인에서 경로가 udpate 됐던 쿼리문은 취소가 되지만
- 오브젝트 스토리지에는 이미 기존 이미지가 삭제되고, 새로운 이미지가 업로드된 채로 복구되지 않습니다,,,^^;;
- 해결... 할 수 있다면....... 해... 보겠...
- 게시글에는 하나의 메서드에 여러 쿼리가 묶여 있지 않아서 `@Transactional` 데코레이터 추가 안 했습니다.
- user와 auth에서 트랜잭션 처리 필요하신 부분이 있다면 추가해주세요~~
- Close: #215

[refactor] 타임라인에 트랜잭션 적용

---

iOS/traveline/Sources/Core/Base/BaseViewModel.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift
iOS/traveline/Sources/Feature/LoginFeature/VC/LoginVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/MyPostListScene/VC/MyPostListVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/ProfileEditingScene/VC/ProfileEditingVC.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/VC/SideMenuVC.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/ViewModel/TravelViewModel.swift

🌱 작업한 브랜치
- feature/#255
- 기존 @Published에서 CurrentValueSubject 방식으로 수정
원래 @ Published로 구현된 state를 바인딩해서 뷰를 업데이트하고 있는데요.
@ Published의 경우, willSet 시점에 publish를 하여 값이 변경되기 직전에 호출됩니다.
그렇기 때문에 VC에서 바인딩한 후 관찰하는 state는 변경되지 직전의 상태가 되는데요.
https://stackoverflow.com/questions/58676249/difference-between-currentvaluesubject-and-published
이를 해결하기 위해서 CurrentValueSubject를 사용해서 State를 관리하도록 수정했습니다.
해당 Subject는 didSet 시점에 publish하기 때문에 업데이트된 값을 바라볼 수 있습니다.
하지만 해당 subject는 private(set)이나 let을 통해 선언해도 어디서든 send() 메서드를 통해 state가 변경될 가능성이 존재했는데요.
이를 위해 AnyPubliser<State, Never> 형태로 방출된 값을 받을 수만 있는 state를 생성했습니다.
```Swift
// BaseViewModel.swift
private let stateSubject: CurrentValueSubject<State, Never> = .init(.init())
var state: AnyPublisher<State, Never> { // VC에서 viewmodel.state로 바인딩
return …
```

[refactor] ViewModel State 수정

---

BE/src/auth/auth.service.ts

🌱 작업한 브랜치
- feature/#282
- 재로그인 시 500이 뜨는 에러를 해결
- bannedIp가 null인 경우 예외처리를 하지 않아 발생한 문제
- close #282

[fix] 로그인 시 500 에러 해결

---

iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Core/Extension/String+.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/WriterDTO.swift
iOS/traveline/Sources/Data/Repository/PostingRepositoryImpl.swift
iOS/traveline/Sources/DesignSystem/View/TLList/TLInfoView.swift
iOS/traveline/Sources/DesignSystem/View/TLList/TLListCVC.swift
iOS/traveline/Sources/DesignSystem/View/TLSearch/TLSearchInfoView.swift
iOS/traveline/Sources/Domain/Model/SearchQuery.swift
iOS/traveline/Sources/Domain/Model/SearchResult.swift
iOS/traveline/Sources/Domain/Model/Travel/TravelListInfo.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/View/HomeListView.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeAction.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeSideEffect.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift

- 검색 결과, 필터링 서버 연결
- 연관 검색어 서버 연결
🌱 작업한 브랜치
- feature/#261
- 페이지네이션을 위해 `SearchQuery`에 `offset`과 `limit`을 관리하고 있습니다!
- 서버분들께 여쭤본 결과 `offset`은 1부터 페이지 넘버를 나타내고, `limit`은 한 페이지에 몇 개의 데이터를 가져올 지를 나타냅니다. 만약 `offset` 1에 `limit` 20을 주면 1~20 결과를, `offset` 2에 `limit` 20을 주면 21~40 결과를 반환합니다!
- `SearchQuery`에도 기본값을 1과 20으로 지정해두었고, 변경가능하도록 했습니당
- `scrollViewDidScroll(_:)`에서 바닥까지 스크롤한 걸 감지해서 페이지네이션 진행했습니당
- 이 과정에서 바닥에 도착했을때 계속 호출하는걸 방지하기 위해 `isPaging` 변수를 추가했어요!
- 홈 -> 페이지네이션 -> 필터 적용 -> 다시 로드
- 홈 -> 검색 -> 키워드로 로드 (기존 검색 필터는 초기화)
- 검색 -> 필터 적용 -> 다시 로드 -> 취소 -> 홈에 저장된 필터로 다시 로드
- 위와 같은 플로우로 진행되게 됩니덩
- 기존에 Extension으로 문자열의 CommonPrefix 범위를 계산해서 색상을 변경해줬는데, 서버 연결하고 보니 Prefix가 아니라 내부에 문자열이 포함되어 있는 경우도 검색이 되더라구요?!
- 그래서 내부 문자열의 범위에 색상을 변경할 수 있도록 수정했습니다 :)
- 홈 화면과 검색 결과 화면에서 필터를 적용했을 때, 종종 충돌 (Crash)가 …

[feat] 검색 결과 서버 연결

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Core/Extension/Data+.swift
iOS/traveline/Sources/Core/Extension/String+.swift
iOS/traveline/Sources/Data/Network/API/AuthEndPoint.swift
iOS/traveline/Sources/Data/Network/API/LoginEndPoint.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Network/API/TimelineDetailEndPoint.swift
iOS/traveline/Sources/Data/Network/API/TimelineEndPoint.swift
iOS/traveline/Sources/Data/Network/API/UserEndPoint.swift
iOS/traveline/Sources/Data/Network/Base/EndPoint.swift
iOS/traveline/Sources/Data/Network/Base/HeaderType.swift
iOS/traveline/Sources/Data/Network/Base/MultipartData.swift
iOS/traveline/Sources/Data/Network/Base/NetworkManager.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelineDetailRequestDTO.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift

🌱 작업한 브랜치
- feature/#256, #267
- multipart 구현
- 타임라인 생성 API 연동
- headers 타입 변경
기존 방식이 HeaderType을 잘 사용하지 못하는 방식이라는 생각이 들어서
Endpoint 내부 headers 타입을 HeaderType으로 선언해뒀습니다.
NetworkManager의 reqeust 시점에서 .value로 접근해서 [String: String] 타입을 받아오는 구조입니다.
```Swift
var header: HeaderType {
return .authorization
}
```
이제 이렇게 사용하실 수 있습니다 ~
1. MultipartData 프로토콜 채택해 request 구조체 생성
2. header 타입 .multipart로 설정
TimelineDetailEndPoint 쪽 보시면 바로 이해가 되실 것 같아요 :)
image와 여러 필드들을 넣을 수  있도록 multipart 구현했습니다.
어떻게 현재 구조를 그대로 가져가면서 편리하게 사용할 수 있을까 고민하다가 Mirror()를 사용하게 되었는데요.
Mirror를 통해 구조체 내부의 프로퍼티들을 mirror의 children들에서 label과 value의 형태로 받아올 수 있습니다.
```Swift
struct ReqeustDTO {
let id: String
}
let reqeust: ReqeustDTO = .init(id: "0inn")
```
이렇게 request를 만들고 값을 보면
- label: id
- value: 0inn
이 되겠군요. …

[feat] Multipart 구현 및 타임라인 생성 API 연동

---

BE/src/postings/repositories/postings.repository.ts

🌱 작업한 브랜치
- be-feature/#287-mine-fix
- 내가 작성한 게시글 반환하는 쿼리문에서 `posting.createdAt` → `p.createdAt`으로 변경
- 언제 alias가 바뀐 거지... 다른 곳은 다 p로 잘 되어 있는데 저 부분만 posting이었다.
- Close: #287

[fix] 내가 작성한 게시글 목록 반환 에러 해결

---

BE/src/postings/dto/create-posting.dto.ts

iOS 요청에 따라 게시글 생성 시 다중 선태 가능한 태그의 선택 개수 제한 폐지!
🌱 작업한 브랜치
- be-feature/#290-limit-free
- 아주 간단히 `@ArrayMaxSize(3)` 데코레이터를 제거했습니다 ㅎㅎ
- Close: #290

[refactor] 게시글 생성 시 테마, 누구랑 태그의 3개 개수 제한 폐지

---

iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelineDetailResponseDTO.swift
iOS/traveline/Sources/Data/Repository/TimelineDetailRepositoryImpl.swift

상세화면 디테일 API 호출을 했어요.
🌱 작업한 브랜치
- feature/#289
-상세화면 디테일 API 호출을 했습니다.
사진이 안뜨던 이유는 responseDTO에서 imageURL로 되어있고 서버에서는 image로 되어있어서 이미지가 누락됐었습니다..
image로 이름 변경 후 잘 사진 잘 받아옵니다.
핸드폰 스크린샷이고 화질이 안좋긴하네요 ㅠ
<image src=https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/9b28373e-0503-4c34-9493-c50d9ca6fee2 width=350>
- Resolved: #289

[feat] 상세화면 API 호출

---

iOS/traveline/Sources/App/SceneDelegate.swift
iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/AuthEndPoint.swift
iOS/traveline/Sources/Data/Network/Base/HeaderType.swift
iOS/traveline/Sources/Data/Network/Base/NetworkManager.swift
iOS/traveline/Sources/Data/Network/DataMapping/AppleLoginRequestDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/ErrorResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/LoginResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/RefreshResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/WithdrawalResponseDTO.swift
iOS/traveline/Sources/Data/Repository/AuthRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Auth/AppleLoginRequest.swift
iOS/traveline/Sources/Domain/Model/Auth/TLToken.swift
iOS/traveline/Sources/Domain/RepositoryInterface/AuthRepository.swift
iOS/traveline/Sources/Domain/UseCase/AutoLoginUseCase.swift
iOS/traveline/Sources/Domain/UseCase/LoginUseCase.swift
iOS/traveline/Sources/Domain/UseCase/SettingUseCase.swift
iOS/traveline/Sources/Feature/LoginFeature/AutoLoginScene/VC/AutoLoginVC.swift
iOS/traveline/Sources/Feature/LoginFeature/AutoLoginScene/ViewModel/AutoLoginViewModel.swift
iOS/traveline/Sources/Feature/LoginFeature/VC/LoginVC.swift
iOS/traveline/Sources/Feature/LoginFeature/ViewModel/LoginViewModel.swift
iOS/traveline/Sources/Feature/MyPageFeature/SettingScene/VC/SettingVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/SettingScene/ViewModel/SettingViewModel.swift

- 로그인, 로그아웃, 회원탈퇴 시 화면 분기 처리
🌱 작업한 브랜치
- feature/#286
- AutoLoginVC를 만들어서 첫 화면으로 사용하고 있습니다.
- AutoLoginVC -> refresh 시도 -> 로그인 화면 or 메인 화면 이동
- 로그아웃, 회원탈퇴 시 SceneDelegate에서 rootViewController를 loginVC로 변경해줍니다.
- AutoLoginVC -> refresh 실패 -> 로그인 -> 로그아웃 -> loginVC
- AutoLoginVC -> refresh 성공 -> 메인 -> 탈퇴 -> loginVC
AutoLoginVC 구현하고 LoginVC 서버 연결 파일 옮겼더니 코드양이 좀 많네용 ,,
PR을 급하게 작성하다보니,, 영상을 참고해주세용
아무래도 이곳저곳에 로딩뷰가 필요해보입니다,,
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/9a3f63b7-3741-43ce-93b0-28e76c33f213
- Resolved: #286

[feat] 로그인 화면 분기 처리

---

BE/src/postings/repositories/postings.repository.ts

addWhere()로 조건을 추가했었는데, 현재는 아예 쿼리문처럼 문자열로 where문을 하나로 처리했다.
🌱 작업한 브랜치
- be-feature/#310-search-filter
- 기존엔 쿼리 조건문을 `andWhere()`로 처리했는데, 이게 왜인지 OR로 동작을 하여서...
- ~~그럼 orWhere()랑 andWhere()는 뭔 차이임...~~
- 아예 `where()` 메서드 하나에 모든 조건을 담도록... 수정
- `p.title LIKE :keyword AND (p.location = :location0 OR p.location = :location1) AND (JSON_CONTAINS(p.theme, :theme0))` 이런 식으로 하나의 조건으로 묶어버리기!
- Close: #310

[fix] 검색 시 각 태그 필터링이 OR로 연결되는 문제 해결

---

BE/package-lock.json
BE/package.json
BE/src/storage/storage.module.ts
BE/src/storage/storage.service.ts
BE/src/timelines/timelines.constants.ts
BE/src/timelines/timelines.controller.ts
BE/src/timelines/timelines.service.ts
BE/src/users/users.module.ts

🌱 작업한 브랜치
- be-feature/#313-greenEye
- uuid 재설치!
- `이미지 유해성 검사 요청 메서드` & `그 검사 결과를 통계(?라고 하긴 좀 빈약한)를 내고, 유해한 이미지라고 에러를 반환하는 메서드`를 StorageService에 추가
- 기존 `upload` 메서드에서 위 두 가지 메서드를 포함하도록 수정했기 때문에, 따로 조치를 취하지 않아도 기존에 upload 메서드를 사용하고 있던 **사용자 프로필 사진 등록/수정, 타임라인 이미지 등록/수정** 과정에서 자동으로 유해성 검사를 진행하게 됩니다~~
- chore 커밋은 정말 허드렛일이라서 확인 안 해주셔도 됩니다~
- [노션](https://www.notion.so/a3ce8f3c918849adbc963864da19b18e)에 아주 대충(,,,) 사진 유해성 검사 API 연동 방법과 몇 가지 사진들로 테스트한 결과 정리해 놓았습니다~! 혹시 궁금하시면 확인해주셔도 좋을 것 같아요 😊
|기능|스크린샷|
|:--:|:--:|
|유해한 이미지가 포함됐을 때 에러 메시지|![image](https://github.com/boostcampwm2023/iOS07-traveline/assets/62174395/45c94447-042b-4a5f-a974-18355a72b567)|
- Close: #313

[feat] 이미지 유해성 검사 API 사용

---

iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/View/HomeListView.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeAction.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift

- 홈 화면에서 끌어내려 새로고침을 구현했습니닷
🌱 작업한 브랜치
- feature/#314
- RefreshControl을 통해 끌어내렸을 때 새로고침 되도록 구현했습니다~!
- 서버 응답 왔을 때 바로 refreshControl 꺼주니까 너무 또 금방 (거의 깜빡) 거리면서 끝나서, 0.5초 딜레이를 일단 넣어놔봤어용
refreshControl 색상을 main 컬러로 지정해봤는데 괜찮은가요?? 그냥 default가 더 나은가 싶기도 하고,, 의견 주시면 감사드림다 🫡
|main|default|
|:--:|:--:|
|![IMG_9921](https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/2df39af1-fc6a-460a-a132-427b30ec2e71)|![IMG_9922](https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/dc0cc28a-ac51-47b7-ba69-38cff3e4a801)|
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/94a18630-2b88-4d5d-8d3b-4286555df619
- Resolved: #314

[feat] 홈 화면 새로고침 구현

---

iOS/traveline/Sources/DesignSystem/Component/TLTag/TLTag.swift
iOS/traveline/Sources/DesignSystem/View/TLList/TLInfoView.swift

🌱 작업한 브랜치
- feature/#323
- 리스트 셀 재사용 시에 이미지만 초기화해주고 있었는데, Tag들의 제목 또한 초기화해주었습니다.!
- 그리고 `TLTag`에서 제목을 변경했을 때 `intrinsicContentSize`를 다시 계산하게 해서 해결할 수 있었습니다 :)
N/A
|변경 전|변경 후|
|:--:|:--:|
|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/b4d38c81-5e98-4792-9ff7-ce99b60b50d6" width="400">|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/7839b9c5-fc5e-4280-90e0-1a26a1bcf7cb" width="400">|
- Resolved: #323

[fix] 검색 리스트 셀 재사용 문제 해결

---

iOS/traveline/Sources/Core/Enum/TagType.swift
iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/PostingEndPoint.swift
iOS/traveline/Sources/Data/Network/Base/NetworkManager.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingDetailResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/PostingRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/PostingRepositoryImpl.swift
iOS/traveline/Sources/DesignSystem/View/TLTagList/TLTagListView.swift
iOS/traveline/Sources/Domain/Model/Filter/FilterDetail/RegionFilter.swift
iOS/traveline/Sources/Domain/Model/Tag.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineSample.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineTravelInfo.swift
iOS/traveline/Sources/Domain/Model/Travel/TravelEditableInfo.swift
iOS/traveline/Sources/Domain/RepositoryInterface/PostingRepository.swift
iOS/traveline/Sources/Domain/UseCase/TimelineUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TravelUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineDateHeaderView.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TravelInfoCVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/View/RegionBottomSheetVC.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/View/SelectTagView.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/ViewModel/TravelViewModel.swift

🌱 작업한 브랜치
- feature/#279
- 여행 수정 API
- 여행 삭제 API
- 여행 신고 API
- 여행 좋아요 API
업데이트하는 모델을 info 전체로 하여 내부에 day 필드를 추가해뒀습니다.
ViewModel에서 해당 day를 관리하게 되고, 바뀔 때마다 헤더가 업데이트됩니다.
기존에 깜빡거리는 이슈는 animating을 false로 줘서 해결했습니다.
하단 카드 리스트는 개인적으로 좀 애니메이션이 있는 게 예뻐서 추가했는데 다른 의견 있으면 말해주십쇼 ^~^
여행 수정 시, TravelVC에 해당 TravelInfo를 넘겨주는 방식으로 구현했습니다.
먼저 수정하기라는 뷰가 Info를 서버에서 받아온 후 활성화 되기 때문에 다시 API 콜 하지 않고, 넘겨주는 방식을 선택했습니다.
- 여행 작성: makeTravelVC()
- 여행 수정: makeTravelVC(info: 값)
이런 방식으로 두 가지 분기처리를 했습니다.
사실 수정해도 전이랑 내용이 같다면 완료 버튼이 활성화되지 않아야 하지만
현재 그것까지 고려하기 힘들것 같아. . 일단 수정의 경우 처음 수정하기 전까지는 무조건 [완료] 버튼이 비활성화 되도록 처리했습니다.
dropFirst()를 사용했습니다.
https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/79336191-fb3e-4c72-a926-ca592993038c
- Resolved: #279

[feat] 여행 관리 API 연결

---

iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeAction.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/ViewModel/HomeViewModel.swift

🌱 작업한 브랜치
- feature/#333
- 여행 작성, 수정, 삭제 후 홈 화면으로 돌아왔을 때 다시 리스트를 불러올 수 있도록 적용했습니다!
- 1페이지부터 다시 데이터를 받아오게 됩니다.
- viewDidAppear에 action이 추가됨에 따라 첫 화면 진입 시 중복해서 서버 요청 보내는 문제를 viewDidLoad action을 제거해 해결했습니다 :)
페이지네이션 테스트까지는 마쳤으나 다른 부분 케이스들은 모두 다 테스트해보진 못했습니다,,
아마 문제가 없을 것 같긴한데 혹시나 다른 부분에서 문제가 발생하면 바로 말씀주시면 수정하겠슴다!
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/d24502ef-07c3-4cee-8fa8-cc70511d5717
- Resolved: #333

[chore] 홈 화면 노출 시 리프레시 적용

---

iOS/traveline/Sources/Feature/MyPageFeature/ProfileEditingScene/VC/ProfileEditingVC.swift

프로필 아이디가 변경되지않던 이슈를 해결했어요.
🌱 작업한 브랜치
- feature/#345
프로필 수정화면에서 아이디가 변경되지않던 이슈 해결
확인해보니 키보드 입력 시 뷰모델로 액션을 보내주는 부분이 지워져있었읍니다..
이 커밋 때 지워진 것 같고, 이제 다시 잘 동작합니다 :)
https://github.com/boostcampwm2023/iOS07-traveline/commit/907ceec410c8ab91abb8857b03c478d78f023280
- Resolved: #345

[fix] 프로필 아이디 수정 안되던 이슈 해결

---

BE/src/timelines/timelines.controller.ts
BE/src/timelines/timelines.repository.ts

🌱 작업한 브랜치
- be-feature/#350-isOwner
- 타임라인 조회 시 repository 대신 queryBuilder 사용하도록 수정
- request['user']의 id 값과 writer의 id 값 비교하여 isOwner 필드 추가
- Close: #350

[refactor] 타임라인 반환 (timelines/:id) 시 isOwner 필드 추가

---

iOS/traveline/Sources/Core/Extension/String+.swift
iOS/traveline/Sources/Data/Network/API/TimelineDetailEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelinePlaceResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/TimelineDetailRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/TimelineDetailRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelinePlace.swift
iOS/traveline/Sources/Domain/RepositoryInterface/TimelineDetailRepository.swift
iOS/traveline/Sources/Domain/UseCase/TimelineWritingUseCase.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/LocationSearchVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/View/PlaceTVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift

🌱 작업한 브랜치
- feature/#334
- 장소 검색에 주소 필드 추가
- 검색 결과 페이지네이션 구현
- 대소문자 관계없이 같은 문자열로 인식하도록 수정
기존에 기본 cell을 사용하고 있었는데 주소 라벨이 추가됨에 따라 새로운 cell인 PlaceTVC를 생성했습니다.
offset 파라미터를 추가하는 방향으로 전체적으로 수정했습니다.
장소 검색 가장 아래 페이지에 닿으면 didScrollToBottom를 방출하고, WritingVC에선 이를 구독해서 offset을 변경시켜줍니다.
이 때, throttle(1초)를 걸어둬서 1초내로 오는 응답(didScrollToBottom)에 대해선 처리하지 않도록 했습니다.
현재 place에 빈값을 보내면 500에러가 뜨는데요.
""키워드인 경우에 결과 리스트를 아예 비워야 하므로 해당 로직을 TimelineWritingUseCase에 추가해뒀습니다 !
- Resolved: #334

[feat] 타임라인 장소 검색 추가 구현

---

iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/TimelineDetailEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelineDetailResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/TimelineDetailRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/TimelineDetailRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineDetailInfo.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineDetailRequest.swift
iOS/traveline/Sources/Domain/RepositoryInterface/TimelineDetailRepository.swift
iOS/traveline/Sources/Domain/UseCase/TimelineDetailUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TimelineWritingUseCase.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/ViewModel/TimelineDetailViewModel.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/View/SelectImageButton.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift

🌱 작업한 브랜치
- feature/#329
- 현재 삭제는 정상적으로 작동하고, 타임라인으로 돌아왔을 때 정상적으로 업데이트 되고 있습니다!
- 다만 지금 수정에서 아래 여러가지 문제가 발생하고 있는데요.. 더이상 수정하자면 시간이 오래 걸릴 수 있을 것 같아 일단 PR 올립니더,,,,,,
1. 지속적으로 수정 시 다운샘플링이 중복 적용 (기 공유된 사항)
2. 수정 화면에서 이미지 갤러리에서 선택 시 간헐적으로 버튼에 이미지가 업데이트 되지 않는 현상
3. 수정 화면에서 기존 이미지가 있을 때 이미지 갤러리에서 선택 시 업데이트 안되거나, 글자 입력 시 기존 이미지로 바뀌는 현상
4. 이미지만 변경했을 시 완료 버튼 활성화 되지 않음
4-1. 해당 원인은 이미지 데이터를 가져오는 시점을 완료 버튼 눌렀을 때로 변경하게 되었는데 (TimelineDetailVC에서 받아온 이미지는 String이기 때문에) 이 때문이 아닌가 싶긴합니다.
5. ~~수정 성공 후 다시 TimelineDetail 화면으로 pop 되었을 때 Detail이 업데이트 되지 않는 현상~~
- ~~해당 부분을 TimelineDetailVC의 viewWillAppear로 처리해두었고, 서버 통신도 성공하지만 뷰가 업데이트 되지 않는 것인지 서버 데이터가 변경되지 않은 것인지 확인이 안되었습니다.~~
- 해당 부분 Hashable 문제로 파악돼서 해결했습니다~!
너무 많은 문제가 남아버렸네요,,,,,, 죄송함니다 😢
영상에는 반영 안됐지만 지금 수정하고 Detail로 넘어가면 수정사항 반영됩니다! …

[feat] 타임라인 상세 수정, 삭제 연결

---

BE/src/postings/postings.service.ts
BE/src/timelines/timelines.service.ts

thumbnailPath, imagePath, avatarPath
🌱 작업한 브랜치
- be-feature/#364-imagePath
- 이미지 path 필드 추가
- thumbnailPath
- iamgePath
- avatarPath
- UsersService에서 사용자 정보를 반환할 때도 avatarPath를 반환하려고 했지만, 반환 DTO에 avatarPath가 없어서 해당 필드를 함께 반환하려면
- UserInfoDto에 avatarPath를 추가하거나
- 해당 메서드의 반환 타입에서 UserInfoDto를 지우거나
- 해야 하는데 둘 다 제가 섣불리 건드리긴 좀 그러하여 ㅎㅎ... 사용자 정보 반환 쪽은 수정 안 했습니다.
- 혹시 필요하다면 수정해주시면 될 것 같아요!
- Close: #364

[chore] image URL 반환 시 image Path 필드도 함께 반환하게 함

---

iOS/traveline/Sources/Core/Extension/Future+.swift
iOS/traveline/Sources/Domain/UseCase/AutoLoginUseCase.swift
iOS/traveline/Sources/Domain/UseCase/HomeUseCase.swift
iOS/traveline/Sources/Domain/UseCase/LoginUseCase.swift
iOS/traveline/Sources/Domain/UseCase/MyPostingListUseCase.swift
iOS/traveline/Sources/Domain/UseCase/ProfileEditingUseCase.swift
iOS/traveline/Sources/Domain/UseCase/SettingUseCase.swift
iOS/traveline/Sources/Domain/UseCase/SideMenuUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TimelineDetailUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TimelineUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TimelineWritingUseCase.swift
iOS/traveline/Sources/Domain/UseCase/TravelUseCase.swift

- Future Extension을 통한 Future-Task 개선
🌱 작업한 브랜치
- feature/#373
- 아래와 같이 Future Extension에 convenience init으로 async 응답을 Future publisher로 변환할 수 있도록 구현했습니다!
~~~swift
/// async 응답 결과를 Future publisher로 변환합니다.
/// - Parameter asyncFulfill: 변환할 async 응답
convenience init(_ asyncFulfill: @escaping () async throws -> Output) {
self.init { promise in
Task {
do {
let result = try await asyncFulfill()
promise(.success(result))
} catch {
promise(.failure(error))
}
}
}
}
~~~
- 사용하는 곳에서는 아래와 같이 async한 결과 값을 넘겨주면 됩니다 ㅎ
- 기존과 동일하게 비즈니스 로직 처리 후 return 해주시면 됩니다!
~~~swift
func fetchSearchList(with query: SearchQuery) -> AnyPublisher<TravelList, Error> {
return Future {
let travelList = try await self.repository.fetchPostingList(with: query)
return travelList
}.eraseToAnyPublisher()
}
~~~
- 코드 뎁스도 얕아지고 좀 더 …

[refactor] Future-Task 개선

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Data/Network/API/TimelineDetailEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelineTranslatedResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/TimelineDetailRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/TimelineDetailRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineTranslatedInfo.swift
iOS/traveline/Sources/Domain/RepositoryInterface/TimelineDetailRepository.swift
iOS/traveline/Sources/Domain/UseCase/TimelineDetailUseCase.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/ViewModel/TimelineDetailViewModel.swift

🌱 작업한 브랜치
- feature/#380
- TimelineDetail 화면에서 번역하기 선택 시 description 번역 기능을 연결했습니다!
- 번역된 정보와 아닌 정보를 따로 관리해서 이후에 수정하기 선택 시에는 번역되지 않은 정보를 넘기도록 했습니다!
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/e4f223d6-95cb-49f8-b63e-811bd11a73ec
- Resolved: #380

[feat] 번역하기 API 연결

---

BE/src/timelines/timelines.service.ts

🌱 작업한 브랜치
- be-feature/#388-image-rollback
에러가 발생했을 때 기존에 스토리지에서 삭제/저장한 이미지를 어떻게 rollback 할까 고민하던 중...
단순히 try ~ catch문으로 해결할 수 있단 걸 깨달았습니다 ㅎㅎ... 타임라인 생성과 수정에만 롤백 기능이 필요하고, 삭제할 때는 필요가 없더군요!
- 타임라인 생성 시
- 스토리지에 이미지 A 저장 (저장 경로를 변수에 할당)
- SQL문 처리
- 만약 SQL문 처리 과정에서 에러가 발생하면, catch문에서 스토리지에서 이미지 A 삭제
- 타임라인 수정 시
- 상황: 기존 스토리지에 이미지 A 저장되어 있고, 변경하려는 이미지는 X
- 로직
- 스토리지에 이미지 X 저장 (저장 경로를 변수에 할당)
- 모든 SQL문 처리
- return 직전에 기존 이미지 A 삭제
- 만약 SQL문 처리 과정에서 에러가 발생하면, catch문에서 스토리지에서 새로 저장한 이미지 X 삭제 (이미지 A는 그대로 존재함)
- 타임라인 삭제 시 (코드 변화 없긴 합니다!)
- SQL문 처리
- return 직전에 스토리지에서 이미지 X 삭제
- 만약 SQL문 처리 과정에서 에러가 발생하더라도, 아직 스토리지에서 이미지 X가 삭제되지 않았으므로 별도 try ~ catch문 필요 없음
반복되는 try ~ catch문을 interceptor로 만들어서 처리해볼까 했는데, 스토리지에 새로 저장하는 이미지의 경로는 동적으로 변수에 할당되기 때문에 interceptor 코드에서 어떻게 알아낼 수 없을 것 같더라고요. 메서드를 실행하면서 알 수 있는 …

[feat] 이미지 rollback 기능 구현

---

BE/src/timelines/timelines.service.ts

🌱 작업한 브랜치
- be-feature/#399-image-delete
- 이미지가 전송되지 않을 시 이미지 필드를 null로 초기화하는 else문을 추가했습니다
- Close: #399

[fix] 타임라인 이미지 제거 시 예전 이미지 URL이 반환되는 문제 해결

---

iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/ViewModel/TimelineDetailViewModel.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/View/SelectImageButton.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift

- 타임라인 수정 / 삭제 간 발생하던 문제들을 해결했습니다~!
🌱 작업한 브랜치
- feature/#383
- 현재 다른 기능들은 정상작동하나, **이미지를 삭제하는 수정 작업**을 했을 시 타임라인 리스트 조회 혹은 상세 조회 시에 기존 이미지 URL이 그대로 넘어오고 있는 문제를 발견했습니다!
- 백엔드분들께는 디스코드로 공유드린 상태이고, 혹시 백엔드 문제가 아닐 시에는 다시 한 번 디버깅이 필요할 듯 합니닷
자꾸 하나 고치면 하나 안되는 상황이 반복되어서 밀고 첨부터 다시 고쳤더니 시간이 좀 걸렸습니다.. ㅎ
커밋 단위로 메세지 확인해보시면 문제 원인 확인하실 수 있습니다~!
https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/dd2c6582-c42d-4849-857c-771a866a6d57
close #383

[fix] 타임라인 수정 / 삭제 간 문제 해결

---

iOS/traveline/Sources/Data/Network/DataMapping/TimelineDetailResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/TimelineResponseDTO.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineCardInfo.swift
iOS/traveline/Sources/Domain/Model/Timeline/TimelineDetailInfo.swift
iOS/traveline/Sources/Domain/UseCase/TimelineWritingUseCase.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineCardView.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/View/SelectedLocationButton.swift

- 타임라인 상세 글 작성 시 장소 등록하지 않았을 때 조회되지 않는 문제를 해결했습니다!
- 디스코드에 경미님이 공유 주신 부분 관련입니당
🌱 작업한 브랜치
- feature/#401
- 위와 같이 장소를 등록하지 않았을 때 place가 null 로 넘어오는데, 기존에 디코딩하던 ResponseDTO 들에서 place가 nullable하지 않아 디코딩 에러가 발생하고 있었습니다~!
- DTO 들에서 place를 옵셔널로 수정하고, 이에 따른 모델들의 수정 작업이 있었습니다.
- 타임라인 상세 화면에서 등록된 장소가 없다면 장소를 노출하지 않도록 수정했습니다!
N/A
| | |
|:--:|:--:|
|![IMG_0235](https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/2900247a-596d-444b-913c-27a551b0f10f)|![IMG_0234](https://github.com/boostcampwm2023/iOS07-traveline/assets/51712973/17f47f14-69c7-4806-80bc-ebbdeaa11540)| -->
- Resolved: #401

[fix] 타임라인 상세 글을 장소 등록 없이 작성했을 때 조회가 되지 않는 문제 해결

---

iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlist.swift
iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Data/Network/Base/EndPoint.swift
iOS/traveline/Sources/DesignSystem/View/TLList/TLInfoView.swift
iOS/traveline/Sources/Domain/UseCase/LoginUseCase.swift
iOS/traveline/Sources/Feature/MyPageFeature/ProfileEditingScene/VC/ProfileEditingVC.swift
iOS/traveline/Sources/Feature/SideFeature/SideScene/View/ProfileLabel.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/View/TimelineCardView.swift

🌱 작업한 브랜치
- feature/#
- 로그인 시 UserDefaults 유저 정보 초기화
- 이미지 뷰들 contentMode 전부 scaleAspectFill로 변경
탈퇴 > 로그인 시 이전 유저 정보가 남아있어서 이걸 지울 시점이 필요했는데요.
어차피 다시 로그인한다면 결국 정보를 모르고 있는 게 나을 것 같아서 로그인 할 때, 해당 유저 정보 UserDefaults값 삭제되도록 구현했습니다 ~ !
앞선 PR 머지된 이후에 머지할게요 ~ ! (브랜치를 거기서 땄네요 ㅎ)
|사이드바|이미지 수정|
|:--:|:--:|
|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/442cbad0-0e76-44c1-8c21-528b95732a4a" width=280>|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/9c0e9605-3e36-4a51-bd67-ae61171d6072" width=280>|
- Resolved: #412

[Fix] QA 반영 (사이드바 버그 및 이미지 비율 수정)

---

iOS/traveline/Sources/App/RootContainerVC.swift
iOS/traveline/Sources/Core/Delegate/ToastDelegate.swift
iOS/traveline/Sources/Core/Delegate/UIViewControllerToastDelegate.swift
iOS/traveline/Sources/Core/Extension/UIViewController+.swift
iOS/traveline/Sources/DesignSystem/View/TLToastView.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/ProfileEditingScene/VC/ProfileEditingVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/ProfileEditingScene/ViewModel/ProfileEditingViewModel.swift
iOS/traveline/Sources/Feature/TimelineDetailFeature/TimelineDetailScene/VC/TimelineDetailVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/VC/TimelineWritingVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineWritingScene/ViewModel/TimelineWritingViewModel.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift

- 토스트 메세지 노출이 필요한 곳에 토스트 메세지를 연결했습니다!
🌱 작업한 브랜치
- feature/#398
1. 타임라인 작성 -> 상세 화면 간
2. 타임라인 상세 -> 타임라인 화면 간
3. 타임라인 -> 홈 화면 간
4. 프로필 수정 -> 홈 화면 간
- 토스트 메세지를 연결하는 과정에서 이전 화면에 해당 메세지를 전달해서 표시해줘야 했는데요..!
Combine + 바인딩을 이용하려 했는데, 아래와 같이 대부분 VC들이 이미 바인딩을 통해서 노출되는 상태에서 다시 한 번 VC에 바인딩을 하는게 뭔가 어색하게 느껴져서,, (바인딩 안에서 또 바인딩)
delegate를 통해 토스트 메세지를 전달하도록 구현한 상태입니다!
해당 방식이 괜찮을지..? 의견 주시면 감사드립니다! 🙇🏻
~~~swift
func bindListView() {
homeListView.didSelectHomeList
.withUnretained(self)
.sink { owner, idx  in
let id = owner.viewModel.currentState.travelList[idx].id
let timelineVC = VCFactory.makeTimelineVC(id: TravelID(value: id))
timelineVC.delegate = owner
owner.navigationController?.pushViewController(
timelineVC,
animated: true
)
}
.store(in: &cancellables)
~~~
이렇게 구현함에 따라 같은 형식의 delegate가 여러개 생성되었습니다. …

[feat] 토스트 메시지 노출

---

iOS/traveline/Sources/Core/Constant/UserDefaultsList.swift
iOS/traveline/Sources/Domain/UseCase/AutoLoginUseCase.swift
iOS/traveline/Sources/Domain/UseCase/LoginUseCase.swift

- 앱 삭제 후 재진입 시 로그인 화면으로 이동하기 위해 첫 진입 (로그인) 여부를 저장합니다.
🌱 작업한 브랜치
- feature/#407
- UserDefaultsList에 `isFirstEntry`를 추가했습니다!
- 앱을 켰을 때 자동 로그인 시도 시 해당 필드를 검증해 자동 로그인 대신 로그인 화면으로 이동합니다.
- 최초 로그인 성공 후 앱 재진입 시 자동 로그인을 시도합니다.
N/A
- Resolved: #407

[chore] 앱 삭제 후 재진입 시 로그인 화면으로 이동하기 위해 UserDefaults에 첫 진입 (로그인) 여부 저장

---

iOS/traveline/Sources/Feature/SideFeature/SideScene/View/ProfileLabel.swift

프로필 사진 기본 이미지로 변경 시 사이드 바에 바로 적용되도록 수정해요.
🌱 작업한 브랜치
- feature/#416
- 프로필 변경에서 기본 이미지로 변경 후 사이드 바에 바로 적용되지 않던 버그를 고쳤어요.
UserRepository에서 데이터가 UserResponseDTO -> Profile로 처리되는 과정에서 imageURL이 nil이면 ""로 변환되는데 
이렇게 사이드 바까지 넘어온 Profile.imageURL이 ""일 경우에 대한 처리가 되지않아서 기본 이미지가 바로 적용되지 않았습니다.
사이드 바의 프로필 이미지를 패치 요청하기 전에 ""일 경우 nil을 넣어서 처리해줬습니다.
https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/59b26072-74b5-44cd-8184-ae0b9edae868
- Resolved: #416

[fix] 프로필 기본 이미지 변경 시 사이드 바 즉시 적용

---

BE/src/auth/auth.controller.ts
BE/src/auth/auth.module.ts
BE/src/auth/auth.service.ts
BE/src/auth/dto/kakao-login-request.dto.ts
BE/src/auth/dto/login-request.dto.interface.ts
BE/src/socialLogin/kakao-login-strategy.ts
BE/src/socialLogin/social-login-strategy.interface.ts

🌱 작업한 브랜치
- be-feature/#421-kakao
- 소셜 로그인 전략 인터페이스 및 카카오 구현체 생성
- login, withdraw 메서드 有
- 카카오 로그인(회원가입) 구현
- 카카오 계정 회원의 탈퇴 구현
- 새로 작성한 메서드와 구분하기 위해 authService의 기존 애플 관련 로직에는 Apple을 붙여 놓았어요! 전략 패턴에 맞춰 소셜 로그인을 구현하고 싶어서 애플 관련 코드? 구조?도 리팩토링할 계획입니다 ㅎㅎ 그래서 나중에 엔드 포인트가 바뀔 수도 있을 것 같아요.
- Resolved: #

[feat] 카카오 소셜 로그인 및 탈퇴 구현

---

BE/src/auth/auth.controller.ts

🌱 작업한 브랜치
- be-feature/#438-login-dev-router
- `login/dev` 라우터가 `login/:social` 라우터보다 먼저 등록되도록 순서 변경
- `login/:social`과 `withdraw/:social` 라우터에서 `social` 관련 Swagger 등록
- `@ApiParam` 데코레이터로 경로 파라미터 social의 설명과 enum 등록
- Resolved: #438

[fix] 소셜 로그인과 개발용 로그인 라우터 순서 변경 & 경로 파라미터 관련 Swagger 추가

---

iOS/traveline/Sources/Core/Constant/Literal.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift

🌱 작업한 브랜치
- feature/#446
리젝 이슈로 차단하기 기능 추가합니다.
우선적으로 UI 및 기능 작업 완료했습니다.
기존 신고하기를 누르더라도 "타임라인 삭제를 완료했어요!" 팝업이 뜨는 오류도 함께 해결했습니다.
... 더보기 란에서 볼 수 있는 menu 타입을 담은 enum 클래스 생성해서 관리해주도록 했습니다.
추후에 기능 추가가 있을 때도 해당 코드를 참고하면 될 것 같아요.
현재 삭제에 실패해도 성공 케이스의 토스트가 뜨는 상황이었습니다.
이에 기존에 만들어둔 errorDescription을 사용해 errorMsg 상태 값 업데이트하도록 했습니다.
state.errrorMsg를 VC쪽에서 바인딩해서 실패 토스트 띄울 수 있습니다.
|차단하기 UI|차단 성공|차단 실패|
|:--:|:--:|:--:|
|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/230bb659-65a3-4bd1-9653-f07befcab608">|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/3ad41b0b-d89e-418e-b14c-108e68f9132e">|<img src="https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/af9f5073-0bba-470c-a373-a6e96dc91a2f">
- Resolved: #446

[hotfix] 차단하기 기능 UI 구현

---

BE/src/exception/exception.filter.ts

서버 내부 에러는 곧바로 500번대 에러로 재할당하여 정확한 에러 원인 파악이 어려웠다. 따라서 500번대 에러로 할당하기 전에 기존 에러 내용을 로그에 남기도록 수정했다.
🌱 작업한 브랜치
- be-feature/#449-error-log
서버 내부 에러는 곧바로 500번대 에러로 재할당하여 정확한 에러 원인 파악이 어려웠습니다. 따라서 500번대 에러로 할당하기 전에 기존 에러 내용을 로그에 남기도록 수정했습니다.
- Resolved: #449

[chore] 서버 내부 에러 로그 작성하도록 수정

---

iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlist.swift
iOS/traveline/Sources/Data/Network/API/AuthEndPoint.swift

🌱 작업한 브랜치
- feature/#451
- apple 탈퇴하기 endpoint 변경
- info.plist 키 추가
AS-IS : /auth/withdrawal/apple
TO-BE : /auth/withdraw/apple
기존에 build 후에 app store connect에서 missing compliance가 뜨면서 수동으로 None을 선택해줘야했는데요.
이걸 info.plist에 넣어주는 방식으로 변경했습니다 ~ !
- Resolved: #451

[hotfix] apple 탈퇴하기 endpoint 변경

---

BE/src/socialLogin/apple-login-strategy.ts
BE/src/socialLogin/social-login-strategy.interface.ts

🌱 작업한 브랜치
- be-feature/#458
서버 로그 확인 결과 이메일 필드를 받아오는 과정에서 문제가 발생하는 것으로 추측되어 LoginStrategy의 이메일 필드를 선택 반환으로 설정해두었습니다.
애플로그인 부분만 수정하니 타입 충돌이 발생해서 LoginStrategy 부분을 건드렸는데 카카오 로그인 부분과 충돌은 없는지 확인하면 좋을 것 같아요!
- Resolved: #458

[fix] LoginStrategy에서 email 필드 선택적 반환으로 전환

---

iOS/traveline/Sources/Core/Enum/VCFactory.swift
iOS/traveline/Sources/Data/Network/API/UserEndPoint.swift
iOS/traveline/Sources/Data/Network/DataMapping/PostingResponseDTO.swift
iOS/traveline/Sources/Data/Network/DataMapping/UserResponseDTO.swift
iOS/traveline/Sources/Data/Repository/Mock/UserRepositoryMock.swift
iOS/traveline/Sources/Data/Repository/UserRepositoryImpl.swift
iOS/traveline/Sources/Domain/Model/Auth/UserID.swift
iOS/traveline/Sources/Domain/Model/Profile.swift
iOS/traveline/Sources/Domain/Model/Sample/ProfileSample.swift
iOS/traveline/Sources/Domain/Model/Sample/TravelListSample.swift
iOS/traveline/Sources/Domain/RepositoryInterface/UserRepository.swift
iOS/traveline/Sources/Domain/UseCase/TimelineUseCase.swift
iOS/traveline/Sources/Feature/HomeFeature/HomeScene/VC/HomeVC.swift
iOS/traveline/Sources/Feature/MyPageFeature/MyPostListScene/VC/MyPostListVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/ViewModel/TimelineViewModel.swift
iOS/traveline/Sources/Feature/TravelFeature/TravelScene/VC/TravelVC.swift

🌱 작업한 브랜치
- feature/#460
유저 차단 API 연동
유저 차단 API 호출 시 유저 id가 필요하기에 추가해뒀습니다.
(+ 기존 posting id를 TravelID로 관리했기에 UserID 구조체도 생성해뒀습니다.)
timelineVC로 넘어가는 경우는 두 가지가 있는데요.
1. 리스트에서 클릭하여 상세 타임라인 뷰로 진입
2. 여행 생성 후 바로 타임라인 뷰로 진입
이 두가지 경우 중 여행 생성 시에는 userID가 필요하지 않다고 판단했습니다.
userID는 자기 자신이 될거기 때문에 유저 차단 기능을 지원하지 않기 때문이죠.
그래서 VCFactory에서 userID 파라미터는 optional로 선언하고 기본값으로 nil을 추가했습니다ㅏ.
```Swift
static func makeTimelineVC(id: TravelID, userID: UserID? = nil) -> TimelineVC {
// 생략
}
```
|기능|스크린샷|
|:--:|:--:|
|차단하기|![Simulator Screen Recording - iPhone 13 mini - 2024-06-01 at 13 42 43](https://github.com/boostcampwm2023/iOS07-traveline/assets/74968390/3e692859-1fd7-493d-83b1-f0eb775529d7)| 
- Resolved: #460

[feature] 유저 차단 API 연동

---

.github/workflows/deploy.yml

🌱 작업한 브랜치
- be-fix/#480-actions
- static (사진 파일) 볼륨을 설정하였습니다.
- log (서버 로그) 볼륨을 설정하였습니다.
- docker prune으로 미사용 이미지 및 컨테이너를 제거합니다.
- docker container 실행 시 cpu 사용률을 70퍼센트로 지정합니다.
- Resolved: #480

[fix] 배포 스텝 수정
